### PR TITLE
Fix hf mf sim (issue #412)

### PR DESCRIPTION
**Pull request by pwpiwi**
Fix hf mf sim (issue #412):
* more timing fixes
* correctly determine correction bit (taken from @iceman1001's fork)
* add checking of Access Conditions for Read command
* never allow reading KeyA

### CODE REVIEW

**Comment by pwpiwi** [comment]
@maxben14, @cjbrigato: comments?

**Comment by iceman1001** [comment]
... a plea,  @pwpiwi , can you add the FeliCa fpga_hf changes into this fpga_hf.bit.   Keeping track of different fpga bin files is a nightmare to me.

**Comment by pwpiwi** [comment]
I would prefer to build a special iceman-version. I will send it via email.

**Comment by iceman1001** [comment]
There shouldn't be too much changes to it,   just in order to enable FeliCa support in FPGA.
No need to merge the Felica commands or anything into client, since they are very rough about the edges.

**Comment by iceman1001** [comment]
Does this one influence @merlokk  apdu PR?  Maybe we wait until that one is merge?

**Comment by merlokk** [comment]
it looks like there is will be no merge. but lets merge mine and then i will help to merge this (if it will needs)

**Comment by merlokk** [comment]
`This branch has no conflicts with the base branch` - all is ok)

**Pull request merged**
