### PR TITLE
RDV40 compatibility fixes

### PR DESCRIPTION
**Pull request by pwpiwi**
* detect and use RDV40 higher voltage ADC channel for hw tune, hf tune, hw detectreader
* fix mode switching in hw detectreader
* detect Smartcard Slot in hw version
* i2c changes from https://github.com/RfidResearchGroup/proxmark3
* some formatting in proxmark3.h

### CODE REVIEW

**Comment by pwpiwi** [comment]
The smartcard slot detection in `hw version` is guesswork. If some proud owner of a RDV40 would please test. For non-RDV40 it displays
```
SmartCard Slot: not available
```
For RDV40 it should display
```
SmartCard Slot: available
```

**Comment by drandreas** [comment]
detection looks ok:

```
bootrom: rdv40_compatibility/v3.0.1-419-gc2bf177d-suspect 2018-09-19 19:37:47
os: rdv40_compatibility/v3.0.1-419-gc2bf177d-suspect 2018-09-19 19:37:48
fpga_lf.bit built for 2s30vq100 on 2015/03/06 at 07:38:04
fpga_hf.bit built for 2s30vq100 on 2018/09/12 at 15:18:46
SmartCard Slot: available
```

**Comment by pwpiwi** [comment]
Can you please check `hw tune` as well´ ? It should now be able to measure HF voltages higher than 36300mV.

**Comment by drandreas** [comment]
I have "tuned" my antennas so my measurement is not representative. That sed my antennas still break the old barrier:
```
# LF antenna: 46.06 V @   125.00 kHz          
# LF antenna: 29.97 V @   134.00 kHz          
# LF optimal: 46.34 V @   123.71 kHz          

# HF antenna: 41.66 V @    13.56 MHz          
```

**Comment by iceman1001** [comment]
...just a matter of time...

image

**Pull request merged**
