### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by merlokk**
add travis.ci from @pwpiwi repository

### CODE REVIEW

**Comment by merlokk** [comment]
changes here https://github.com/Proxmark/homebrew-proxmark3/pull/15 also needs to be merged.
works without changes in rb file
just need to add environment variable `REPOSITORY_EP` to travis settings. for me it contains `merlokk/proxmark3`

**Comment by merlokk** [comment]
Tested. works. https://travis-ci.org/merlokk/proxmark3

**Comment by merlokk** [comment]
and this:
https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce

In order to streamline our image catalog, on 15 November 2017 we will be simplifying our image offerings to the following:

osx_image: xcode9.1
osx_image: xcode9
osx_image: xcode8.3 (Default)
osx_image: xcode7.3
osx_image: xcode6.4
The following images will be deprecated:

osx_image: xcode8.2
osx_image: xcode8.1
osx_image: xcode8

maybe it needs to check xcode 9 instead of xcode 7.3?

**Comment by merlokk** [comment]
It works. so...
Ready to merge)

**Comment by merlokk** [comment]
lets merge)

**Comment by iceman1001** [comment]
Nop.  I am not convinced about your solution.

**Comment by merlokk** [comment]
What it needs to add?

**Comment by merlokk** [comment]
and now?

**Comment by marshmellow42** [comment]
Adding Travis to master was discussed before, and turned down in favor of forks using it before things are committed.  I'm on the fence myself.

**Comment by micolous** [comment]
I'd like it if proxmark3 was library-like enough that we can run some tests.  But this wouldn't handle a lot of platform specific issues, particularly weird serial communication issues on single platforms -- which I'd argue is the biggest risk.

**Comment by merlokk** [comment]
OK. you dont need to config travis on proxmark and so on. lets just add this file to master. and if someone needs to use travis - he just setup it. if dont needs - there will be just one unused file in the root...

**Comment by pwpiwi** [comment]
It is not "just an unused file in the root". Pulling from this repository will overwrite each developers .travis.yml file. I am not convinced that we should do that.

Proposal: we could add a directory "Testing" which would include the testing related files (the appveyor file would go there too) and some instructions how to use it.

**Comment by merlokk** [comment]
ok, i will change the PR

**Comment by merlokk** [comment]
as for appveyor: move it too?

**Comment by pwpiwi** [comment]
I would propose: yes.

**Comment by merlokk** [comment]
moved.

**Comment by merlokk** [comment]
can be merged?

**Comment by merlokk** [comment]
merge plz)

**Pull request merged**
