### PR TITLE
Add PSK, space to tabs, new trace, bug fixes to clock & demods

### PR DESCRIPTION
**Pull request by marshmellow42**
changed leading spaced to tabs (why it looks soo large)
fixed bugs in detectaskclock function (kept counting on every loop through and didn't reset)
switched to using size_t for sizes in lfdemod.c
added new psk/nrz demod commands
added new hid trace.

### CODE REVIEW

**Comment by marshmellow42** [comment]
I guess hold that thought.  I will work to resolve the conflicts.

**Comment by marshmellow42** [comment]
I think I've resolved the conflicts while keeping my changes...

**Comment by marshmellow42** [comment]
should be good to go, let me know if there are any concerns.

**Comment by holiman** [comment]
The only concern I have is that iceman's commits touches a lot of the same files. I spent some time today going through it, almost ready to commit.. There'll be some merging required after this....

**Pull request merged**
