### PR TITLE
improve `hf 14a info`

### PR DESCRIPTION
**Pull request by merlokk**
added detect prng type to `hf 14a info` from @iceman1001 fork. Thanks)

### CODE REVIEW

**Comment by pwpiwi** [comment]
crapto1 is a separately developed library. I therefore wouldn't change/extend it if not necessary. Otherwise it becomes more difficult to update it when new versions come out.

I propose to add the new function to mifarehost.c instead.

**Comment by merlokk** [comment]
done

**Comment by iceman-1** [comment]
Given the fact blapost said he is not releasing any more code,
And the latest v3.3 was released several years ago,
I would say its NO chance at all of a new release of crapto1 in the future. 

But of course I can be wrong and locus will fall from the sky.

**Comment by pwpiwi** [comment]
Please add a line to CHANGELOG.md

**Comment by merlokk** [comment]
done #460

**Comment by iceman1001** [comment]
the problem here, shows why we have divide from "info" and "reader" commands.
The prng test is only interesting when looking at a crypto1 enabled tag,  ie,  it should be  "hf mf info"
since its a extended test against the tag.  Not a normal function test. 

it should not be inside  "hf 14a info"  or "hf 14a reader" ...   but the discussions here is void.  just blindly merge and push things.   This behavior will be the downfall of PM3 repo.

**Comment by merlokk** [comment]
Now we dont have hf mf info. Maybe we can push there some sak check, but now I dont see any other functionality in hf mf info than prng ( it needs to create this command and place there pprng function?

**Comment by pwpiwi** [comment]
We have "reader" and "info" commands per low level transmission standards (14a, 14b, 15, ...). Mifare uses ISO14443A and I therefore don't see an issue in showing information on Mifare cards in `hf 14a info` (or ` hf 14a reader` as in your fork).

**Comment by iceman-1** [comment]
you should have seen the nack-bug test, which would also be interesting..
or detection of which mode a Mifare Plus card is in...
or.. well,  let your imagination to lead you instead...

**Pull request merged**
