### PR TITLE
reworking magic cheneese card wipe

### PR DESCRIPTION
**Pull request by merlokk**
added: fill card with default data, keys and access conditions
and some refactoting

### CODE REVIEW

**Comment by merlokk** [comment]
Is this pull request ok?

**Comment by iceman1001** [comment]
I'm not sure why you want to mix in all functionality into csetuid.. 
I would have made a new command instead.

**Comment by pwpiwi** [comment]
@iceman1001: "all functionality" is just adding an option `k` to write blocks with all zeros and a default sector trailer to all sectors. The wipe option `w` is already there but only works for cards which support this command.  If we question the new `k` option we should question the existing `w` option as well.

I would support a merge.

**Comment by Fl0-0** [comment]
A compatibility with magic 4K would be nice, something like `hf mf csetuid k 4` ?

**Comment by merlokk** [comment]
I thought about adding command `hf mf cfill`, but by now i just look at this command because it have option `w` (as it mentioned by @pwpiwi) that works only for one type of "magic" card.
Maybe it shold (after this pull request) to do some refactoring and add this command?

@Fl0-0 I have only one 4k card that not compatible with this type of setting block at all( I need somr investigation to add this card to code.

**Comment by iceman1001** [comment]
The -w wipe option is something that got snuck in there by the chinese who impl the c* cmds.
And it exists in **hf mf csetblk**  so if you gonna add more stuff in csetuid,  then you will need to complete the other one aswell.   Now that is upright stupid to do.  
I would suggest **hf mf cwipe**  command to get rid of this problem.

The suggested -k option is already covered in lua-script.   **script run remagic -h**  

Not to metion the fact that the command is labeled  "cetsuid"  meaning is sets the uid.  Not a mix command with lot of extras.   @piwi, you of all people to support this?   Sometimes I get the feeling you are just trolling. 

@merlokk  I like your effort but I strongly dislike the given structure how it just makes the CLI unclear. 

I don't suppor this PR given the above reasons.

**Comment by merlokk** [comment]
I have not touched any functionality other than this block: '	if (wantFill) {...}'
Just refactor and fix some of not working code.
I have not touched any of current functionality. so all the scripts will work as it worked.

What I can do now?
i will implement `hf mf cwipe` and connect this command to option k?
Or get rid of option `k` and just implement  `cwipe`?

**Comment by iceman1001** [comment]
I suggest you implement **hf mf cwipe**  with "k"  option :)
That will be a clear command structure.   We should also remove the -w  in csetuid, csetblk commands after you have done a "cwipe" command

thank you for your understanding, @merlokk

**Comment by pwpiwi** [comment]
@merlokk: if you can do as @iceman1001 proposed, this would be one step beyond.

**Comment by iceman1001** [comment]
...and when you are at it,  make it support the different sizes..   Mini, 1k,2k,4k    Not hardcode 64blocks..

**Comment by merlokk** [comment]
It needs to rewrite big portion of code because wipe option linked with commands on the arm side.
ok, i will do it after reworking nested functionality/

**Comment by iceman1001** [comment]
hrm,  I just noticed that in PM3 Master doesn't have the wipe-param like I have in icemanfork.  
In my fork it would just had been a matter of add/removing that flag-param on clientside.

**Comment by merlokk** [comment]
As I remembered it was there)...   Maybe someone's refactoring kill it... I look.

**Comment by merlokk** [comment]
All is OK)
added additional command hf mf cwipe
maybe it needs to delete wipe functionality from hf mf csetblk? at least from pc side? and dont touch the arm side?

**Comment by merlokk** [comment]
now it really ok)
as i see there is some strange behavier of the chineese card) sector0 = sector16 for 1kb card.
so if we dont guess size of card it simply rewrites....

**Comment by merlokk** [comment]
all is ok? or it needs to be improved som way?

**Comment by pwpiwi** [comment]
Give us some time to check. In the meantime please update CHANGELOG.MD.

**Comment by merlokk** [comment]
done)

**Comment by pwpiwi** [comment]
Please declare static functions as static (those which have no extern declaration in the header file).

**Comment by merlokk** [comment]
done 719970fc058a9330ecff2d594ebf8b4c868ac100

**Pull request merged**
