### PR TITLE
Fix iso15693 fpga

### PR DESCRIPTION
**Pull request by pwpiwi**
This is an attempt to fix issue #916. I didn't find a real root cause because results were inconsistent when building old commits. Which makes me think that there might have been a timing at the edge between working and not working.

### CODE REVIEW

**Comment by g3gg0** [comment]
ready to go for a merge?

**Comment by pwpiwi** [comment]
I am ready. You finished testing?

**Comment by g3gg0** [comment]
had to port my code to the new codebase and i cannot get 'hf 15 sim' to work properly.
seems the reader (a closed 3rd party device) cannot receive data properly.

accessing tags from proxmark seems to work fine, its just the sim that was/is also odd.

**Comment by g3gg0** [comment]
ah wait, i have another idea what it could be

**Comment by g3gg0** [comment]
okay resolved. it was just a merge error involving this branch.
everything works fine now and i will prepare a PR for ISO15693 SLIX-L functions as soon this is in master.

**Pull request merged**
