### PR TITLE
hitag2 write

### PR DESCRIPTION
**Pull request by henjo**
Hi,
I have added a writer function for hitag2 in crypto mode. I have only tested it on a Honda Civic key so far so there might be problems with other tags.

Usage is similar to hitagS write:
lf hitag write 24 KEY pagenumber 32bitvalue

Best regards,
Henrik

### CODE REVIEW

**Comment by marshmellow42** [comment]
looks good, unfortunately i have no cards to test it :(   but it compiles fine on mingw 4.9.2...  
could you add a note about the command to the changelog.md?

**Comment by henjo** [comment]
sounds good, i added the changelog entry

**Comment by iceman1001** [comment]
Great contribution,   regretfully I have the same issue as marshmellow42 , ie no cards to test on. 

But I suggest we merge anyway and sort out the potential issues as we go.

**Comment by iceman1001** [comment]
Noone is able to test this PR?

**Comment by iceman1001** [comment]
@marshmellow42   @pwpiwi   merge?  it looks like nobody can verfiy this one

**Comment by marshmellow42** [comment]
I feel we should merge this before it goes stale.

**Comment by pwpiwi** [comment]
Agreed. Unfortunately this is quite common: nobody wants/can test before it is in HEAD. Let's go for it.

**Pull request merged**
