### PR TITLE
fix SAK problem in iso14443a select procedure. very old bug)

### PR DESCRIPTION
**Pull request by merlokk**

### CODE REVIEW

**Comment by merlokk** [comment]
@iceman1001 you have this bug too(

**Comment by merlokk** [comment]
found here...
http://www.proxmark.org/forum/viewtopic.php?id=2175

**Comment by merlokk** [comment]
let me double check. it seems just need to change comment

**Comment by iceman-1** [comment]
The 6bit, not sure if the Pm3 thread says anything specific of it. 
The discuss is about 8bit sak. 

Where has the protocol definition to say of bit6 ? 
Not even sure why the test for bit6 is in the code.

**Comment by merlokk** [comment]
PICC compilant with iso14443a-4  ====1
http://dl.shibby.fr/Documents/Access%20Control/13.560MHz/MIFARE/m018413.pdf

**Comment by pwpiwi** [comment]
BIt 6 == 1 indicates that the card is compliant to iso14443-4, meaning that card activation needs an additional step, i.e. RATS and PPS.

The code therefore was OK. If bit 6 is 0, then return 2 (ATS not supported). Otherwise continue with the RATS sequence.

**Comment by merlokk** [comment]
code was OK, but comment not OK(  and in mifare identification procedure not OK too(

**Comment by pwpiwi** [comment]
Yes, comment should explicitely refer to 14443-**4** 

What's wrong with the type identification document?

**Comment by merlokk** [comment]
there is big red rectangle on this bit. and it seems comment was from this document

**Pull request closed without merging**
