### PR TITLE
fido fix

### PR DESCRIPTION
**Pull request by merlokk**
fido fix.

do not merge! needs to check emv

### CODE REVIEW

**Comment by merlokk** [comment]
fixed #773

**Comment by merlokk** [comment]
EMVExchangeEx ?

**Comment by merlokk** [comment]
or maybe rewrite 
```
	if (Result[*ResultLen-2] == 0x61) {
		uint8_t La = Result[*ResultLen-1];
		uint8_t get_response[5] = {apdu[0], ISO7816_GET_RESPONSE, 0x00, 0x00, La};
		return EMVExchangeEx(channel, false, LeaveFieldON, get_response, sizeof(get_response), Result, MaxResultLen, ResultLen, sw, tlv);
	}
```

because here may be not only 1 block. 
here may be several blocks one by one.

**Comment by merlokk** [comment]
there is an external loop here
https://github.com/Proxmark/proxmark3/blob/master/client/fido/fidocore.c#L183

maybe make different command like `EMVExchangeAll` or like that and put there this logic?
and move there all the functionality with GetData command

**Comment by pwpiwi** [comment]
I see. But don't we need such alloop for the EMV functionalities as well?

Let's merge first to fix the broken fido command...

**Pull request merged**
