### PR TITLE
fixed #395

### LINKED ISSUE #395: Compile issue on Rolling Kali 2017.02
Was seeing the following when following the instructions in the wiki:

> #make clean && make all
> cmdhfmf.c: In function ‘CmdHF14AMfCWipe’:
> cmdhfmf.c:1908:14: error: ‘TRUE’ undeclared (first use in this function)
>    wipeCard = TRUE;
>               ^~~~
> cmdhfmf.c:1908:14: note: each undeclared identifier is reported only once for each function it appears in
> Makefile:274: recipe for target 'obj/cmdhfmf.o' failed
> make[1]: *** [obj/cmdhfmf.o] Error 1
> make[1]: Leaving directory '/root/proxmark3/client'
> Makefile:33: recipe for target 'client/all' failed
> make: *** [client/all] Error 2

Modifying 'TRUE' to 'true' on line 1908 of cmdhfmf.c and recompiling seems to have resolved the issue.

### PR DESCRIPTION
**Pull request by merlokk**
fixed #395

### CODE REVIEW

**Comment by merlokk** [comment]
now its ok.

but. do you know how to avoid all this changes appear here?

**Comment by pwpiwi** [comment]
You had modified your local copy of master. I had squashed the miriad of your commits into one when I accepted your PR. But your local copy still contains all your commits.

I recommend to start over with a fresh master (git clone) and create a separate branch for each of your changes. After the change is committed, you can simply delete your branch. And you can keep your local copy of master up to date by doing a git pull from time to time.

**Comment by marshmellow42** [comment]
I find git rebase works best as long as you keep up regularly.

**Comment by merlokk** [comment]
@marshmellow42  it needs no commits after master merge at local repository?

**Pull request closed without merging**
