### PR TITLE
increase NESTED_SECTOR_RETRY value to get all keys

### PR DESCRIPTION
**Pull request by kingbobi**
fix for #479

### CODE REVIEW

**Comment by merlokk** [comment]
10 by default is ok. If someone want to increase this he can increase it into his sources.
200 will be too slow in general.

**Comment by kingbobi** [comment]
At 10, it doesn't find all the keys. This means that the function does not work properly.

**Comment by pwpiwi** [comment]
Why do we limit the number of iterations at all? Sooner or later it should find every key. Abort with Button if impatient?

**Comment by merlokk** [comment]
Button not needs. Maintenance cycle on client side.

**Comment by merlokk** [comment]
Maybe add there optional to not limit iterstions?

**Comment by pwpiwi** [comment]
Or the time?

**Comment by merlokk** [comment]
For time will needs a parameter but we have complicated parameters structure in nested now.

**Comment by marshmellow42** [comment]
Why is button press to cancel not valid?

It appears isOK has a test for button was pressed while in nested... Sure you might have to hold it a minute...  But it should cancel.

**Comment by merlokk** [comment]
It must work. But stop from client will be faster

**Comment by micolous** [comment]
I believe this will depend on a combination of the card and the antenna.  I've had to increase Mifare Classic authentication retries doing "genuine" authentication on Android, using the phone's NFC chipset.  I've had plenty of times where a MFC card would reject authentication with a valid key around a quarter the time.

I can't say I've seen the same on PM3, except when my antenna had problems.

Maybe there should be a set of runtime-configurable parameter for Mifare retries in general?  This would help people with bad cards and bad antennae.

**Comment by iceman1001** [comment]
So, nobody likes this PR.   close?

**Pull request closed without merging**
