### PR TITLE
fix hf iclass sim

### PR DESCRIPTION
**Pull request by pwpiwi**
* sim 2: add responses to read(1) (Config) and read(5) (AIA)
* sim 2/3: don't restrict CC to 00 bytes only
* sim 3: add responding to read block commands
* sim 2/3: add responding to READ_CHECK_KC
* fix sizes of pre-encoded tag answers
* sim 2: change default card challenge
* remove commented code
* use #defines instead of numerical constants for simulation modes
* some reformatting and whitespace fixes
* fix debug print on unhandled commands
* deduplicate: use sim functions from iso15693.c
* fix times in tracelog and 'hf list iclass' (sim only)
* don't check parity in 'hf list iclass'
* fix timing in TransmitTo15693Reader()
* add simulation of block 3 and 4 (Kd and Kc) reads
* add simulation of READ4 (4 blocks read)
* FPGA change (hi_simulate.v): avoid spp_clk phase changes
* chg to reader command decoder in iso15693.c (require no modulation before SOF)
* add 'has_been_low_for' logic to hi_simulate.v (same as in other FPGA modes, default to "no modulation")
* add simulation of chip status (IDLE, ACTIVE, SELECTED, HALTED)
* check ACSN on SELECT
* add simulation of RESELECT
* always check length of reader commands
* fix printing of NR, MAC in sim 2 mode
* fix response length to CHECK command
* implement UPDATE and CHECK[Kc]
* add simulation of multiple pages (PAGESEL by @sherhannn9)
* maintain cipher states per page
* update cipher state after UPDATE commands (@sherhannn9)
* add simulation of personalization mode
* respond with SOF on HALT
* display "\<SOF\>" instead of "0f" in 'hf list iclass'
* standard LED handling
* speedup CodeIso15693AsTag()
* TransmitTo15693Tag(): don't send unmodulated start of SOF
* reduce modulation depth in hi_simulate.v

### CODE REVIEW

**Comment by pwpiwi** [comment]
No changes to the low level timings yet. Completing the simulated command set.

**Comment by pwpiwi** [comment]
Tag response timing is OK now. Reader command decoding needs to become more reliable.

**Comment by iceman1001** [comment]
Always happy to see where you get your inspiration from.   Do feel free to make a PR to RRG/Iceman repo.

**Comment by sherhannn79** [comment]
'hf iclass sim 3' not work? :)

**Comment by pwpiwi** [comment]
Can you be more specific?

**Comment by sherhannn79** [comment]
> Can you be more specific?

On enter of 'hf iclass sim 3'
replay  'Undefined simtype 3'

I solved the problem by changing line 199 in cmdhficlass.c to
} else if (simType == ICLASS_SIM_MODE_CSN
|| simType == ICLASS_SIM_MODE_CSN_DEFAULT
|| simType == ICLASS_SIM_MODE_FULL) {

**Comment by pwpiwi** [comment]
Oops. Fixed. Latest commit includes other fixes for issues reported in forum as well.

**Comment by pwpiwi** [comment]
Added the implementation of UPDATE and CHECK[Kc] based on @sherhannn79.

**Comment by pwpiwi** [comment]
Added simulation of multiple pages and personalization mode (thanks to @sherhannn79 again). Now also handles cipher states per page. SOF only responds are now displayed as `<SOF>` in 'hf list iclass'.

@sherhannn79: this has become quite a big change and I would like to merge it to master before going further. I have no matching reader/card pair and therefore cannot test authentication. Can you please do some tests and final fixes? I would then leave further sim improvements to you and concentrate on read/write/snoop.

**Comment by sherhannn79** [comment]
@pwpiwi Yes, I am ready to do tests soon. Unfortunately, I now have urgent matters. I hope that I can do the tests in the next day.

**Comment by pwpiwi** [comment]
Take your time. We do this for fun and unsalaried.

**Pull request merged**
