### PR TITLE
some coverity fixes plus fix fdx help

### PR DESCRIPTION
**Pull request by marshmellow42**

### CODE REVIEW

**Comment by iceman1001** [comment]
I still suggest we fill the path_vars with zeros.   Otherwise I see no problem with merging this one

**Comment by marshmellow42** [comment]
I was concerned with affecting timing as I did not look into the calling of this function.  I prefer to let piwi have a look at something like that.

**Comment by marshmellow42** [comment]
it doesn't look like it should impact any timing issues...  @pwpiwi ok to add the memsets?

**Comment by pwpiwi** [comment]
The "+1" shouldn't be necessary because the format template is already longer than the string itself. And the memset shouldn't be necessary because the string operations add the trailing 0 byte.

**Comment by marshmellow42** [comment]
i get the trailing 0 byte is added with sprintf.
i now also see that the macro would translate to "bitflip_%d_%03hx_states.bin" which should be 2 characters longer than the actual filenames.  so you are 100% correct.

however, can we leave this in so as to remove the coverity warning as it should not hurt anything?

**Comment by pwpiwi** [comment]
Sure. I think we can afford wasting one more byte to keep coverity scan happy :grin:

**Comment by marshmellow42** [comment]
because of the Merge remote-tracking branch 'upstream/master' commit i suggest this pull gets squashed during the merge, `Squash and Merge` option to keep things cleaner...

**Pull request merged**
