### PR TITLE
Reclaim more than 19K of ARM flash memory.

### PR DESCRIPTION
**Pull request by pwpiwi**
- added compiler options -fdata-sections and -ffunction-sections (thanks to iceman for the hint)
- removed float operations from common/lfdemod.c to avoid adding float libraries to the ARM os image
- moved the fpga images to the data section to avoid reserving unused space for a separate section

### CODE REVIEW

**Comment by iceman1001** [comment]
Great @pwpiwi!
I tested the -O2 vs -Os    270 vs 294.  That was a big difference but I also noticed that my pm3 got slower. Maybe I imagined the increase of speed, but it felt snappier with the -O2 ..   
You mentioned something about apply this parameter for some parts, we should definetley do that.

**Comment by marshmellow42** [comment]
This commit breaks FSK reading acurracy as it creates larger rounding errors.  In my fork I have a way to do it without floats.

**Comment by marshmellow42** [comment]
EDIT:  let me do further tests.  My previous comment may have actually been a different problem.

**Comment by marshmellow42** [comment]
I take it completely back, your math works fine.  I would ask though, could you remove this file from this commit so I can commit my more significant changes to lfdemod.c (i'll include your changes).

I am just now creating a pull request that refactors and removes a some duplicate code (funny I was working on removing the floats as well. (but I like yours better)).

**Comment by pwpiwi** [comment]
@marshmellow42: lfdemod changes reverted...

**Comment by holiman** [comment]
Good job there @pwpiwi

**Comment by marshmellow42** [comment]
am i correct in saying there is no longer any need to flash the fpga?

**Comment by marshmellow42** [comment]
hmmm.  after flashing my pm3 is on an endless reset loop.  i can reflash if i hold the button but it doesn't help.  - windows user

**Comment by marshmellow42** [comment]
oy
sorry didn't flash the bootrom nevermind

**Comment by pwpiwi** [comment]
Technically speaking, you never flashed the FPGA with the flasher tool :grin:. The FPGA configuration files go into the ARM memory, just like the OS. Up to now a separate section had been reserved for this purpose, now it goes into the same section like any other initialized data.

The OS now starts at another memory address (where the FPGA configuration had been before) - therefore the bootloader needs to be updated.

**Pull request merged**
