### PR TITLE
HW TUNE adapting for powerful antennas.

### PR DESCRIPTION
**Pull request by iceman1001**
CHG:  'hw tune'  adapting LF measuring from ( >> 8) max 65v,  to ( >>9 ) max 130v in the graph data.   Max LF voltage is 140.8v to measure.

Added a delay for antenna coil and caps to power up before measuring,
removed a variable in ReadAdc

### CODE REVIEW

**Comment by pwpiwi** [comment]
Are there such antennas?

**Comment by iceman1001** [comment]
Would I make a PR if it wasn't needed?

**Comment by pwpiwi** [comment]
Of course you wouldn't :smile: . I am rephrasing my question: which antennas give such a high voltage?

**Comment by iceman1001** [comment]
Tailormade ones

**Comment by pwpiwi** [comment]
You make me curious. How do you achieve the high Q? Ferrit core? Litze?

**Comment by marshmellow42** [comment]
I am also curious about the benefit of a stronger antenna as a comment made years ago about the current hardware indicated anything above 47v would harm readability.  
"There isn't much point going higher than 40V as the zenners will clip the voltage"

http://www.proxmark.org/forum/viewtopic.php?id=90

**Comment by pwpiwi** [comment]
Good point. In fact it should not even be possible to see values above 47V due to the Zener diodes.

**Comment by marshmellow42** [comment]
So is there a board design that has different zeners?

**Comment by pwpiwi** [comment]
Not sure about the Zeners. But I remember posts claiming that there are boards with a "tuned" voltage divider R30/R31.

**Comment by iceman1001** [comment]
@marshmellow42  is on to something  :)  Of course its a new board.  None of the existing ones can handle it because of the zenner diodes.

**Pull request merged**
