### PR TITLE
lf viking and iclass

### PR DESCRIPTION
**Pull request by gustothebun**
add lf viking
add Iclass write

### CODE REVIEW

**Comment by marshmellow42** [comment]
Hmm didn't want to wait for my adjustments?  I am close to having a push ready.  :(

**Comment by gustothebun** [comment]
Hi Marshmellow,

     I am having difficulty, I need more help  I can delete it in the
morning, the write functionality have problem, it wrote sometimes and does
not sometimes, depending on the contents. Please don't get upset, I want
the clone function to work. Really need help on it.
In fact I'll delete it now.

Cheers,

Gusto the bun

**Comment by gustothebun** [comment]
I deleted it :) of course I'll wait for u. I have posted asking in coming
iclass topic. sometimes the write function does not work depending on the
blockno and the current contents and content to be written. No one reply me
=(.

I am sorry,

Gusto the bun

**Comment by marshmellow42** [comment]
No worries, you did good getting this to github. :).  I must have missed the forum post.

**Comment by marshmellow42** [comment]
see my iclass branch in my fork.  i'm still cleaning it up a little but the write and clone functions seem to function for me.

**Comment by marshmellow42** [comment]
regarding the Viking cards it appears you take a printed ID and then look for that ID in the bits to "align" the repeating bits.  interesting approach.  is there an example of this tag on the forum?

**Comment by holiman** [comment]
Should I close this PR ?

**Comment by gustothebun** [comment]
So good to hear that. it's my antenna then that cause the problem.

You are the best =)

Cheers

Gusto the bun

**Comment by gustothebun** [comment]
Yes please

**Comment by gustothebun** [comment]
Hi Marshmellow,

    I have modified some code on stand alone mode to perform the elite
attack without pc, I will summit the code to u directly. Previously the
problems with iclass write command I still looking for the solution for
that problem.

Best regards

Gusto the bun

**Pull request closed without merging**
