### PR TITLE
Complete WTX handling (pull request #477)

### PR DESCRIPTION
**Pull request by pwpiwi**
Complete WTX handling (pull request #477)

### CODE REVIEW

**Comment by merlokk** [comment]
needs to think about setting timeout from ATS

**Comment by pwpiwi** [comment]
I did this already some time ago. See `iso14a_set_ATS_timeout(uint8_t *ats)`

**Comment by merlokk** [comment]
i see, have not noticed(
ill look if i change timeout somethere

**Comment by merlokk** [comment]
fixed settings timeout in apdu. now it must work)

**Comment by merlokk** [comment]
lets merge this and #482

**Pull request merged**
