### PR TITLE
Lua lib to set emulator card memory

### PR DESCRIPTION
**Pull request by jamchamb**
```lua
local emu = require('emulator')
...
emu.set_mem(card_data, clear_flag)
```

### CODE REVIEW

**Comment by pwpiwi** [comment]
Looks good. But can you add at least an example script that makes use of the new function?

**Comment by jamchamb** [comment]
Ah, I had modified `iso14443a.c` to use emulator card memory as its `data` buffer in some cases, but that's still hacky and not ready for release (clobbers the SimulateIso14443a function). This was because the max data buffer you can currently pass is 512 bytes due to the size constraint on USB commands. The use case is to pass buffers up to `CARD_MEMORY_SIZE` bytes long to initialize the simulator memory.

If it doesn't make sense to add this yet then I can wait until the new sim code is ready, but I thought it could be helpful.

**Comment by pwpiwi** [comment]
I am not sure if I understand you. In `Mifare1ksim()` we make already use of the emulator card memory (up to 4K) and the existing `MifareEMemSet()` can set all 4K by calling it repeatedly (which you do as well in your lua script). Which changes would be required then in iso14443a.c ?

**Comment by iceman1001** [comment]
@jamchamb  Would you mind applying the needed changes so we can merge this one?

**Comment by jamchamb** [comment]
@iceman1001 I can make the changes but it seems like the example you give me is just for interactive scripts run through the `script` command in the client; this would be for using as a library in other Lua scripts rather than something you directly run from the client. `lualibs/md5.lua` is the only library I can see that does something similar.

**Comment by iceman1001** [comment]
Ok,  Will you add a script which uses your lib?

**Comment by jamchamb** [comment]
I'll close this until I have some good example scripts ready.

**Pull request closed without merging**
