### PR TITLE
Added loading EMV transaction parameters from json file

### PR DESCRIPTION
**Pull request by merlokk**
Added loading EMV transaction parameters from json file.
Added json lib jansson (https://github.com/akheron/jansson). tested on MACOS, Linux, Windows/msys2
And added sketch for next EMV command - scan (starting EMV8 #520)

### CODE REVIEW

**Comment by merlokk** [comment]
ok) lrts check and merge this PR.
I have tested it on win, linus and travis with linux and macos.
it must be ok)

**Comment by pwpiwi** [comment]
You are adding a lot of code to read the 58 lines of the json file.

**Comment by merlokk** [comment]
yes, it for test. i have added `hf emv scan`. and it will use json code to create card profile for emulator or just viewing...

**Comment by merlokk** [comment]
lets merge)

**Comment by pwpiwi** [comment]
Could you please move the jannson directory up one level? We shouldn't have object files in an `include` directory.

**Comment by merlokk** [comment]
maybe ill move it to `client` directory. as th lua libs... ok?

**Comment by merlokk** [comment]
moved

**Comment by merlokk** [comment]
Thanks)

**Pull request merged**
