### PR TITLE
improve appveyor.yml

### PR DESCRIPTION
**Pull request by merlokk**
added test execution timeout 40 sec to avoid hang VM

### CODE REVIEW

**Comment by merlokk** [comment]
as i see it needs no spaces, other symbols and `;` at the end of lines and it shows normally

**Comment by merlokk** [comment]
let it lay here:)
script to execute build of old commit

$token = '-------token here-------'
$headers = @{
  "Authorization" = "Bearer $token"
  "Content-type" = "application/json"
}
$body = @{
    accountName="merlokk"
    projectSlug="proxmark3"
    branch="master"
    commitId="1df4df6"
}
$body = $body | ConvertTo-Json
Invoke-RestMethod -Uri 'https://ci.appveyor.com/api/builds' -Headers $headers  -Body $body -Method POST

**Comment by iceman1001** [comment]
Are you ready with it?  or do you want to change anything more?

**Comment by pwpiwi** [comment]
Is it possible to display the output of the testing scripts?

**Comment by merlokk** [comment]
I can display input and output for test scripts. Needs to do?

**Comment by pwpiwi** [comment]
I think that would be helpful. The grep for a single word is very limited.

**Comment by merlokk** [comment]
done

**Comment by merlokk** [comment]
Grep done(  lets merge this i think what to do because proxmark3 -h creates very big log...

**Pull request merged**
