### PR TITLE
Legic Tag Simulator

### PR DESCRIPTION
**Pull request by drandreas**
Cleaned up Legic Simulator.

I've moved Legic Tag Simulator for easier readability and maintainability into a separate file.
The revised simulator is running from the 212 kHz SSP Clock for better reliability.

### CODE REVIEW

**Comment by Fl0-0** [comment]
Great job !
Thank you.

**Comment by drandreas** [comment]
Thank you for the compliment. I'm surprised that so many ppl are still interested in Legic Prime...

**Comment by drandreas** [comment]
Sorry, I'm not used to writing change logs.

Next time you touch the file, would you add "Changed Legic Prime tag simulator (`hf legic sim`) to run from 212 kHz SSP clock for better reliability (AntiCat)" please?

**Comment by TomHarkness** [comment]
> Sorry, I'm not used to writing change logs.
> 
> Next time you touch the file, would you add "Changed Legic Prime tag simulator (`hf legic sim`) to run from 212 kHz SSP clock for better reliability (AntiCat)" please?

Just copy someone else's example line. It's only one line with your name / alias at the end.

**Pull request merged**
