### PR TITLE
fix t55xx write timing

### PR DESCRIPTION
**Pull request by marshmellow42**
was adjusted with only t55x7 in mind and broke the q5 or t5555. 
basically just reverted to original values.  (added comments for acceptable values per ata5577 docs.)

### CODE REVIEW

**Comment by marshmellow42** [comment]
based on:
http://www.proxmark.org/forum/viewtopic.php?id=2485, and http://www.proxmark.org/forum/viewtopic.php?pid=16624#p16624, and
http://www.proxmark.org/forum/viewtopic.php?pid=16392#p16392
I think the new(old) t55xx timings in the first commit are needed by the community in the next release.

If there is any need to separate the other fixes let me know.  :)

**Comment by iceman1001** [comment]
ready to merge this one?

**Comment by marshmellow42** [comment]
added 2 more bug fixes - 
data psknexwatchdemd would crash if no samples were in the graphbuffer.
and you could not print the hf mfu wrbl or rdbl help without a tag being on the antenna.

**Comment by buggii** [comment]
Good catch! Crashing without a tag on the antenna was a rare but nasty problem even in old versions!

Inviata dal mio dispositivo Android.

-----Original Message-----

**Comment by iceman1001** [comment]
How about someone with the powers do a merge.

**Pull request merged**
