### PR TITLE
#447 part 1

### PR DESCRIPTION
**Pull request by merlokk**
added command `hf 14a info`, 
copy functionality from `hf 14a reader` to `hf 14a info`, 
added command `hf 14a reader` with simple anticollision-select procedure
part of #447

### CODE REVIEW

**Comment by merlokk** [comment]
ready

**Comment by merlokk** [comment]
Lets merge) tomorrow ill put APDU and maybe one part of emv

**Comment by merlokk** [comment]
plz, merge) i need to have this PR in master to create next PR

**Comment by pwpiwi** [comment]
What is the point in having a `hf 14a reader` and an extended version called `hf 14a info` ?

**Comment by merlokk** [comment]
because we add functionality to this command and command becomes not a reader. it like command that getting information about a card.
I can just rename reader to info...  but i think it will be better to have 2 commands

**Comment by pwpiwi** [comment]
Let's assume that we rename `hf 14a reader` to `hf 14a info`. What functionality will the "new" `hf 14a reader` have?

**Comment by merlokk** [comment]
just anticollision-select sequence.

**Comment by merlokk** [comment]
and many people used to use `hf 14a reader` so we dont break user experience...

**Comment by pwpiwi** [comment]
If `hf 14a reader` will be used as a start for further communication with the card (and I think this is what it originally was intended for), then we would need at least an option to prevent RATS. I further suggest to change the help text to "Start acting like an ISO14443 Type A reader". And after displaying the SAK, ATQA, and ATS, an additional "Card <UID> is selected. You can now start sending commands." would clearly show the changed functionality.

**Comment by merlokk** [comment]
OK

**Comment by iceman1001** [comment]
the suggested process is different from all other "reader" commands in the client.
Which are also used in "hf search" in order to fast detect which type of card.

Starting to use "hf 14a reader"   as  a substitute for  "hf 14a raw -s"  seems not very ideal. More as a suggestion that didnt take anything in consideration on current client functional, unless the suggestion is to change all other "reader" functions to act the same,   in that case I would have seen more a discussion since that would be a major change.

**Comment by marshmellow42** [comment]
Btw.  This breaks hf search 14a detection.

**Comment by merlokk** [comment]
@marshmellow42 #456

**Comment by marshmellow42** [comment]
Thanks

**Comment by pwpiwi** [comment]
@iceman1001: we have the `info` commands which are used to tell us everything we want to know about a card. Then what would be the purpose of the `reader` commands?

**Comment by iceman-1** [comment]
A fast cardtype detection

**Comment by pwpiwi** [comment]
why do we need it faster than with the `info` commands?

**Comment by iceman1001** [comment]
As I said before,  for "hf search",   The info command is used for extended extraction of information we deemed interesting.   The reader command is to verify what type it is.  no more no less. 
All extended tests is useless against all 14a enabled cards.   Hence we put a lot of information in "hf mfu info" for example.  But we can, to follow your idea, merge it into "hf 14 reader".   That will be utterly useless exercise but sometimes that is what is needed.

We could have  "hf 14a reader x"  where "x" means  "eXtended information" about the tag.
but we haven't gone down that road either.   Or "v" for "Verbose", same same but different.

But back to your question,
it is obvious, a fast card type detect means automation which further steps can be made,   where you can automatically select possible attack vectors.   There is no need to get a lot of information printed or even run, for this kind of scripting.  

So,  purpose is what you are actually asking about.
"info" command exists to collect information about card.  How is the configuration, lockbits, size, etc.
"reader" command exits to verify which card type, to find which more commands to run.  

Information gathering vs decision making.

**Comment by pwpiwi** [comment]
Proposal: let's have both. Make `hf 14a reader` backwards compatible again (i.e. field off at the end). And add an option to leave field on (and card selected) to start an interactive session with the card.

**Comment by merlokk** [comment]
I can just invert this flag and all will be as you talk.

**Comment by pwpiwi** [comment]
Yes, that would be my proposal and should satisfy all needs. @iceman1001?

**Comment by iceman1001** [comment]
What is needed is a fruitful discuss about how we want to unify the similar commands to behave the same way.  ie,  decide which way it should and we can change all commands accordingly,  i.e. all "hf * reader" commands.   This would be benefital for enduser experience.  This PR shows the lack of needed discuss and shows the downside with open source development.

**Comment by pwpiwi** [comment]
Yes, the discussion has started already. And I agree to your proposal of a tiny `hf xx reader` and a more sophisticated `hf xx info`.

**Comment by marshmellow42** [comment]
+1. As long as chip identification is part of the tiny reader.

**Comment by pwpiwi** [comment]
Ok. Chip identification is used by `hf search` only, correct?

**Comment by merlokk** [comment]
This identification? or  more?
```
proxmark3> hf 14a reader
 UID : 01 02 03 04
ATQA : 00 02
 SAK : 18 [2]
```
and `hf search` uses info command

**Comment by marshmellow42** [comment]
Ultimately hf search should output a chip name if identifiable, like
 mifare classic 1k or compatible
UID xxxxxxx
But nothing else.   The info cmd should output much more imho

**Comment by merlokk** [comment]
from here https://www.nxp.com/docs/en/application-note/AN10834.pdf page 7

**Comment by pwpiwi** [comment]
`hf 14a info` does give a chip name already (among other information) but is based on SAK and ATQA only. AN10834 is about NXP products only. A mix would probably be best.

**Comment by merlokk** [comment]
maybe add simple check to reader and AN10834 check to info? and change call in `hf search` from info to reader?
ok?

**Comment by pwpiwi** [comment]
I would propose all type checks in reader. HF search calling reader. HF info calling reader plus additional output.

**Comment by marshmellow42** [comment]
Info would call reader with a verbose output on and then in the future possibly collect other info like lock/ST info?

Normal reader would not need to output all the specific data it collects to decide what chip, just outputs the chip and uid.  Unless verbose switch is on..

?

**Comment by marshmellow42** [comment]
Well ST info would be mifare specific so that would be part of a mifare info cmd not 14a info...

**Comment by merlokk** [comment]
maybe not verbose = reader, verbose=info?

**Comment by marshmellow42** [comment]
Sure.  But there maybe additional information we would want to collect on info in the future.

**Comment by iceman1001** [comment]
...one reason for two commands,  is maintainability,  to make nice and small functions not filled with complicated if-nested statements and a mess to maintain. 

info - extented / deep information , of the tag.
reader -  well,  the name is bad,  but since we used it since 2008 (more or less)  all guides, posts, tells ppl to use it so Im reluctant to change the command name,  but the name is not good.  

The suggestion from @pwpiwi  of  "info" calling reader,  and does further test is a good one.
keep the "reader" to minimum and old functionality.
all new tests we want to add,  goes into "info"

**Comment by merlokk** [comment]
so
reader - anticollision-select + simple parse SAK/ATQA
info - all the rest

and
`hf search` goes to (new) reader  command

yes?

**Comment by marshmellow42** [comment]
While in principle I'd like it to be that simple, I also think it is important to have hf search's identification to be as accurate as possible so it may not be..  I can't recall what else is built, currently, but I do know sak/atqa isn't enough to fully identify chips.

**Comment by merlokk** [comment]
to fully identify it needs to call `hf 14a info`

**Comment by marshmellow42** [comment]
But maybe we leave it like that and point the user to the appropriate info cmd that will tell them more...  I think that is what we did for ultralight.

**Pull request merged**
