### PR TITLE
fix hf mf sim

### PR DESCRIPTION
**Pull request by pwpiwi**
* fix parity encryption (thanks to Eloff, http://www.proxmark.org/forum/viewtopic.php?id=6347)
* add support to simulate Mifare Mini, Mifare 2K and Mifare 4K
* change to standard LED handling (A: PM is working, B: reader is sending, C: tag is responding, D: HF field is on)
* whitespace

### CODE REVIEW

**Comment by pwpiwi** [comment]
Added another commit to improve simulation. However, I think that a slight speedup of the simulation is required in order to completely convince a legitimate reader.

**Comment by Fl0-0** [comment]
Great work @pwpiwi !

Tested with another proxmark3, a SCL3711 reader / libnfc, a real reader (Vanderbild, access control).

**Comment by pwpiwi** [comment]
Thanks, and yes, it is better than before but still not good yet. I have a new benchmark: the NXP NFC Taginfo app on my smartphone gives inconsistent/random results. On each try I get one of
* "serious errors communicating with the tag" - nothing detected
* "Unknown Mifare class IC, possibly cloned"
* "NXP IC detected"
In addition I notice crashes when starting simulation multiple times. All in all I don't think that the change is ready to merge yet.

**Comment by micolous** [comment]
> I have a new benchmark: the NXP NFC Taginfo app on my smartphone gives inconsistent/random results.

Android interferes with this process by trying to authenticate with `a0a1a2a3a4a5` first, before any application can use it.

Also try out "reader mode" in NXP TagInfo, this uses a different process to read the card, and Android doesn't get to meddle with as many things.  That may make debugging easier.

**Comment by pwpiwi** [comment]
In the end the PM3 'hf mf sim' should behave like a real card. Therefore it shouldn't matter how Android interferes or how an app tries to read a card.

**Comment by pwpiwi** [comment]
Pushed another commit. Fixed the crashes on subsequent `hf mf sim` calls. NXP Taginfo is satisfied now (detects PM3 as genuine NXP ICs). I am satisfied too. 😃 

Agreed to merge? Any other issues?

**Comment by Fl0-0** [comment]
Works great wirh NFC TagInfo too 1K and 4K simulation.

**Pull request merged**
