### PR TITLE
added command `hf list mf`

### PR DESCRIPTION
**Pull request by merlokk**
works:
- last key check
- standard key checks
- weak nested key checks

cant do
- hardnested key checks (coz it too less info about cipherstate....)

done.

### CODE REVIEW

**Comment by iceman1001** [comment]
Nice,  really nice done, bro!

**Comment by pwpiwi** [comment]
Looks great. Just two minor things:
```
cmdhflist.c:330:5: warning: this 'else' clause does not guard... [-Wmisleading-indentation]
     else
     ^~~~
cmdhflist.c:332:6: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'else'
      AuthData.nt_enc_par = parity[0];
```

and please add a line to the CHANGELOG.

**Comment by merlokk** [comment]
thanks) 
done.

**Comment by pwpiwi** [comment]
Another thing to fix: printing keys should be with 12 hex characters instead of 10.

**Comment by merlokk** [comment]
fixed #572

**Pull request merged**
