### PR TITLE
improve lf cmdread

### PR DESCRIPTION
**Pull request by marshmellow42**
create bitbang mode if delay is 0
adjust so use full lf config options are used on read-back (and divisor on send)
turn off antenna at completion
auto run `data samples` at completion

### CODE REVIEW

**Comment by marshmellow42** [comment]
:) it works (on my pm3 at least...)  i'm disappointed in some of the timing stuff.  evidently the loop takes ~ 7us to compute (even when not doing anything to the antenna) and somewhere it appears i am loosing additional time in the when turning on the antenna.  but i don't have accurate equipment to really tell for sure (as right now i'm just using two pm3's).  
all i really do know is i was able to reproduce t55x7 commands with this new bitbang method...

**Comment by iceman1001** [comment]
yup yup,  very good!
still, my blue keyfobs doesn't want to react...  even with your new bitbang..

**Comment by iceman1001** [comment]
We should measure properly with the exact delay times for antenna ON/OFF.   That will improve other LF commands

**Comment by marshmellow42** [comment]
knowing the on off times would be great, but would it change per antenna? or even circuit board?

**Comment by marshmellow42** [comment]
for the blue keyfobs, did you try timings closer to the higher end of the spec?

**Comment by pwpiwi** [comment]
FpgaWriteConfWord() was not meant for timing critical antenna modulation. The transfer of the (16 bit) conf word to the FPGA at a speed of 4Mbit/s takes 4us. And there is a minimum delay of 2us between two transfers.

**Comment by iceman1001** [comment]
6us vs ~7us,   not too bad measured @marshmellow42 ...  Some adjustments in the T55xx timings?

**Comment by pwpiwi** [comment]
The loop itself needs some time as well, and the SPIsetup. 7us might well be the most correct value.

**Comment by marshmellow42** [comment]
The strange thing is the on periods were just about correct, but the off periods were long.  Making me think there is a time loss in both but it takes time for the antenna to power so I only see the issue in the off periods.

**Comment by marshmellow42** [comment]
this would indicate we need to shorten the period_0 by (4us*2 + 2) each round before we go to turn on the antenna. (or i suppose right after we turn off the antenna)
this would require a refactor of the loop and a "pre-priming" the delay periods grouping multiple 1's and 0's together...  this refactored loop will alter the current 7us loop delay that is used.

**Comment by iceman1001** [comment]
? I'm afraid I don't follow now.   The loop has period_1 / period_0,  with delays.  isn't it lesser the perid_0 delay enough?

**Comment by iceman1001** [comment]
aha,  you talk about the fliping state which takes time,  ie  from 1->0 or 0->1,   and not  0-0,  or 1-1..
maybe just trace previous bit and current bit..    counter-1 and counter.

**Comment by pwpiwi** [comment]
> so if the action of sending the FPGAWriteConfWord() to turn on or off the antenna takes 4us

To be clear: `FPGAWriteConfWord()` returns nearly immediately. The transfer itself is done by the hardware and the hardware won't accept new data until transfer and subseqent pause is completed. This explains why you cannot send in shorter periods. Therefore the change of the antenna signal should appear near the end of a `WaitUs(7)`.

No idea why on and off behave differently. May need to look at the hardware in more detail.

**Comment by iceman1001** [comment]
looking at it,
- worst case precision of the used clock.
- surprised the WDT doesn't triggers from the long waits you are using-  // WaitMS(2500); 

The off maybe has some delay in caps which is discharged?

**Comment by pwpiwi** [comment]
The same caps would cause the same delay when charged. But there are none.

**Comment by marshmellow42** [comment]
the long waits were part of the original command and are meant to make sure the tag is powered up fresh and are in a clean state so i left them.

Thanks @pwpiwi for the clarification.  that time it takes to get to the hardware shouldn't really affect what we are trying to do because it is a constant.  every command will take that amount of time and so every command will be timed correctly still.  if we were trying to sync up with an outside clock it might matter, but we are not.

do you think it is possible for the antenna to take longer to turn on than to turn off?

**Pull request merged**
