### PR TITLE
minor iso14443a timing fixes to avoid select errors

### PR DESCRIPTION
**Pull request by pwpiwi**
* take setup frame guard time (SFGT) into account
* adjust iso14a_timeout by FPGA delays
* don't give up on first WUPA. Retry several times

### CODE REVIEW

**Comment by aczid** [comment]
I'm sorry to report that this change breaks ISO14443A card selection on my new proxmark3 v3 (clone). Using the commit directly preceding this merged one results in a working setup for hardnested, everything after is broken for me.
I'd send in a PR but I am out of my depth here.

**Comment by aczid** [comment]
`git checkout db68bcdb06618c97a45a39ff5ed6acf666da62e2 armsrc/iso14443a.c` on HEAD also fixes this issue for me.

**Comment by aczid** [comment]
A little more background about the behavior: normal commands like rdbl work fine, but as soon as many wakeups are performed in sequence, such as when running 'chk' or 'hardnested' the wakeup errors occur.

**Comment by Evert-Arends** [comment]
I can confirm this issue as reported by @aczid .

**Comment by pwpiwi** [comment]
I have to confirm issues with hf mf hardnested.

However, I have no issues at all with hf mf chk. Tested with Mifare Classic, Magic Gen 1, Mifare Plus, Mifare Classic emulation on IDPrime.

**Comment by merlokk** [comment]
May you put here some chk logs?

**Comment by iceman1001** [comment]
Latest offical source,   problems with checkkeys
```
proxmark3> hw ver
[[[ Cached information ]]]
          
Prox/RFID mark3 RFID instrument          
bootrom: iceman/master/ice_v3.1.0-214-g07bf77e1-dirty-unclean 2017-12-04 19:28:33
os: master/v3.0.1-213-gbc3b2f7-dirty-suspect 2017-12-10 09:47:49
LF FPGA image built for 2s30vq100 on 2015/03/06 at 07:38:04
HF FPGA image built for 2s30vq100 on 2017/10/27 at 08:30:59


proxmark3> hf mf chk *1 ?
No key specified, trying default keys          
chk default key[ 0] ffffffffffff          
chk default key[ 1] 000000000000          
chk default key[ 2] a0a1a2a3a4a5          
chk default key[ 3] b0b1b2b3b4b5          
chk default key[ 4] aabbccddeeff          
chk default key[ 5] 1a2b3c4d5e6f          
chk default key[ 6] 123456789abc          
chk default key[ 7] 010203040506          
chk default key[ 8] 123456abcdef          
chk default key[ 9] abcdef123456          
chk default key[10] 4d3a99c351dd          
chk default key[11] 1a982c7e459a          
chk default key[12] d3f7d3f7d3f7          
chk default key[13] 714c5c886e97          
chk default key[14] 587ee5f9350f          
chk default key[15] a0478cc39091          
chk default key[16] 533cb6c723f6          
chk default key[17] 8fd0a4f256e9          

To cancel this operation press the button on the proxmark...          
--#db# ChkKeys: Can't select card (UID) lvl=1          
#db# ChkKeys: Can't select card (UID) lvl=1          
#db# ChkKeys: Can't select card (UID) lvl=1          
#db# ChkKeys: Can't select card (UID) lvl=1          
#db# ChkKeys: Can't select card (UID) lvl=1          
#db# ChkKeys: block=44 key=1. Can't select. Exit...          
.          
No valid keys found.          

```

**Comment by iceman1001** [comment]
ok,  I think I understand.  This change enforces some timing difference and assume method iso14a_get_timeout is called everywhere to get the correct timing.
However plenty places in iso14443a.c the gobal variable iso14a_timeout is directly called missing out on the "corrected time"...

**Comment by pwpiwi** [comment]
Fixed with PR #515. The timeout in GetATQA() was too agressive.

**Comment by aczid** [comment]
Problems with 'chk' only occurred when trying the '*4' dump option for 4k cards.

**Comment by aczid** [comment]
Thank you, I will test on my setup!

**Comment by aczid** [comment]
I'm afraid the issue persists...

**Comment by aczid** [comment]
@pwpiwi the card I am using is a Dutch OV-chip card made by Infineon. I'd be happy to send you one via mail if it helps with testing.

**Comment by pwpiwi** [comment]
Time to send some logs / traces / screenshots please. "issue persists" is not helpfull - especially when it doesn't persist  for me...

**Comment by iceman1001** [comment]
**hf mf hardnested** -  works.
**hf mf chk** - fail
**script run mfkeys** - fail

#db# Authentication failed. Card timeout.
#db# Authentication failed. Card timeout.
#db# Authentication failed. Card timeout.
#db# Authentication failed. Card timeout.

**Comment by merlokk** [comment]
can you check `hf mf chk` with options `s` and `ss`? lets look about timeout...
and ill look last commit tomorrow but maybe it will need to increase default timeout because of changes

**Comment by aczid** [comment]
https://p.6core.net/p/XCU2X4JD4XxXPLEq6L5AKcBP

**Comment by iceman1001** [comment]
https://pastebin.com/gtQVbdPz

**Comment by pwpiwi** [comment]
Found it. Wrong sign in set/get_timeout. I am currently AFK. Will fix tomorrow.

**Comment by pwpiwi** [comment]
Fix pushed to PR #515.

**Comment by aczid** [comment]
I'm afraid it's still not fixed for me and the same behavior remains.
https://p.6core.net/p/6xIEewUFwUBxDA4pxGorX2jp

**Comment by pwpiwi** [comment]
Increase the distance between card and antenna?

**Comment by aczid** [comment]
No matter how I place the card with regards to the antenna I keep getting the same results.

**Comment by pwpiwi** [comment]
I don't get any errors any more.  Not even sporadic.

Please open a new issue. Provide `hw ver`, `hw tune`, and a link to the output of `hf list 14a` after the error occurred.

**Comment by aczid** [comment]
Will do, thanks.

**Pull request merged**
