### PR TITLE
add: proper indentation when printing TLV objects

### PR DESCRIPTION
**Pull request by pwpiwi**
before:
```
proxmark3> hf 14a apdu -s -t 00A404000E325041592E5359532E444446303100
>>>>[sel TLV] 00 a4 04 00 0e 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31 00
<<<< 6f 41 84 0e 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31 a5 2f bf 0c 2c 61 23 4f 07 a0 00 00 00 03 10 10 50 0d 56 69 73 61 20 50 6f 73 74 62 61 6e 6b 9f 0a 08 00 01 05 02 00 00 00 00 bf 63
 04 df 20 01 80 90 00
APDU response: 90 00 - Command successfully executed (OK).
TLV decoded:
--6f[41] 'File Control Information (FCI) Template':
        00: 84 0e 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31 |..2PAY.SYS.DDF01
        10: a5 2f bf 0c 2c 61 23 4f 07 a0 00 00 00 03 10 10 |./..,a#O........
        20: 50 0d 56 69 73 61 20 50 6f 73 74 62 61 6e 6b 9f |P.Visa Postbank.
        30: 0a 08 00 01 05 02 00 00 00 00 bf 63 04 df 20 01 |...........c.. .
        40: 80                                              |.
--84[0e] 'Dedicated File (DF) Name':
        00: 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31       |2PAY.SYS.DDF01
--a5[2f] 'File Control Information (FCI) Proprietary Template':
        00: bf 0c 2c 61 23 4f 07 a0 00 00 00 03 10 10 50 0d |..,a#O........P.
        10: 56 69 73 61 20 50 6f 73 74 62 61 6e 6b 9f 0a 08 |Visa Postbank...
        20: 00 01 05 02 00 00 00 00 bf 63 04 df 20 01 80    |.........c.. ..
--bf0c[2c] 'File Control Information (FCI) Issuer Discretionary Data':
        00: 61 23 4f 07 a0 00 00 00 03 10 10 50 0d 56 69 73 |a#O........P.Vis
        10: 61 20 50 6f 73 74 62 61 6e 6b 9f 0a 08 00 01 05 |a Postbank......
        20: 02 00 00 00 00 bf 63 04 df 20 01 80             |......c.. ..
--61[23] 'Application Template':
        00: 4f 07 a0 00 00 00 03 10 10 50 0d 56 69 73 61 20 |O........P.Visa
        10: 50 6f 73 74 62 61 6e 6b 9f 0a 08 00 01 05 02 00 |Postbank........
        20: 00 00 00                                        |...
--4f[07] 'Application Dedicated File (ADF) Name':
        00: a0 00 00 00 03 10 10                            |.......
--50[0d] 'Application Label':
        String value 'Visa Postbank'
        00: 56 69 73 61 20 50 6f 73 74 62 61 6e 6b          |Visa Postbank
--9f0a[08] 'Unknown ???':
        00: 00 01 05 02 00 00 00 00                         |........
--bf63[04] 'Unknown ???':
        00: df 20 01 80                                     |. ..
--df20[01] 'Unknown ???':
        00: 80                                              |.
proxmark3>
```
after:
```
proxmark3> hf 14a apdu -s -t 00A404000E325041592E5359532E444446303100
>>>>[sel TLV] 00 a4 04 00 0e 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31 00
<<<< 6f 36 84 0e 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31 a5 24 bf 0c 21 61 1f 4f 08 a0 00 00 00 25 01 08 01 50 10 41 4d 45 52 49 43 41 4e 20 45 58 50 52 45 53 53 87 01 01 90 00
APDU response: 90 00 - Command successfully executed (OK).
TLV decoded:
--6f[36] 'File Control Information (FCI) Template':
        00: 84 0e 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31 |..2PAY.SYS.DDF01
        10: a5 24 bf 0c 21 61 1f 4f 08 a0 00 00 00 25 01 08 |.$..!a.O.....%..
        20: 01 50 10 41 4d 45 52 49 43 41 4e 20 45 58 50 52 |.P.AMERICAN EXPR
        30: 45 53 53 87 01 01                               |ESS...
        --84[0e] 'Dedicated File (DF) Name':
                00: 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31       |2PAY.SYS.DDF01
        --a5[24] 'File Control Information (FCI) Proprietary Template':
                00: bf 0c 21 61 1f 4f 08 a0 00 00 00 25 01 08 01 50 |..!a.O.....%...P
                10: 10 41 4d 45 52 49 43 41 4e 20 45 58 50 52 45 53 |.AMERICAN EXPRES
                20: 53 87 01 01                                     |S...
                --bf0c[21] 'File Control Information (FCI) Issuer Discretionary Data':
                        00: 61 1f 4f 08 a0 00 00 00 25 01 08 01 50 10 41 4d |a.O.....%...P.AM
                        10: 45 52 49 43 41 4e 20 45 58 50 52 45 53 53 87 01 |ERICAN EXPRESS..
                        20: 01                                              |.
                        --61[1f] 'Application Template':
                                00: 4f 08 a0 00 00 00 25 01 08 01 50 10 41 4d 45 52 |O.....%...P.AMER
                                10: 49 43 41 4e 20 45 58 50 52 45 53 53 87 01 01    |ICAN EXPRESS...
                                --4f[08] 'Application Dedicated File (ADF) Name':
                                        00: a0 00 00 00 25 01 08 01                         |....%...
                                --50[10] 'Application Label':
                                        String value 'AMERICAN EXPRESS                          '
                                        00: 41 4d 45 52 49 43 41 4e 20 45 58 50 52 45 53 53 |AMERICAN EXPRESS
                                --87[01] 'Application Priority Indicator':
                                        00: 01                                              |.
proxmark3>
```

### CODE REVIEW

**Comment by iceman1001** [comment]
Nice one!   Does this one inflict @merlokk  's other PR??

**Comment by iceman1001** [comment]
still,  should we also have a compressed view?  Now it repeats printing same data but less and less. Yeah I know the nested objectifying but still.

**Comment by pwpiwi** [comment]
Yes, we can avoid duplication if we dump data only for the leaf objects. Can be done... stay tuned..

**Comment by iceman1001** [comment]
How about we merge merlokks emv PR and then adjust this one?

**Comment by pwpiwi** [comment]
Now:
```
proxmark3> hf 14a apdu -s -t 00A404000E325041592E5359532E444446303100
>>>>[sel TLV] 00 a4 04 00 0e 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31 00
<<<< 6f 36 84 0e 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31 a5 24 bf 0c 21 61 1f 4f 08 a0 00 00 00 25 01 08 01 50 10 41 4d 45 52 49 43 41 4e 20 45 58 50 52 45 53 53 87 01 01 90 00
APDU response: 90 00 - Command successfully executed (OK).
TLV decoded:
--6f[36] 'File Control Information (FCI) Template':
        --84[0e] 'Dedicated File (DF) Name':
                00: 32 50 41 59 2e 53 59 53 2e 44 44 46 30 31       |2PAY.SYS.DDF01
        --a5[24] 'File Control Information (FCI) Proprietary Template':
                --bf0c[21] 'File Control Information (FCI) Issuer Discretionary Data':
                        --61[1f] 'Application Template':
                                --4f[08] 'Application Dedicated File (ADF) Name':
                                        00: a0 00 00 00 25 01 08 01                         |....%...
                                --50[10] 'Application Label':
                                        String value 'AMERICAN EXPRESS                          '
                                        00: 41 4d 45 52 49 43 41 4e 20 45 58 50 52 45 53 53 |AMERICAN EXPRESS
                                --87[01] 'Application Priority Indicator':
                                        00: 01                                              |.
proxmark3>
```

**Comment by iceman1001** [comment]
beautiful!

**Comment by iceman1001** [comment]
Now you can hook up your "topaz" TLV  to this one ;)

**Comment by merlokk** [comment]
in my PR there is part of this changes. maybe lets merge)

**Comment by iceman1001** [comment]
Now @merlokk  , you can update your other PR...

**Pull request merged**
