### PR TITLE
EM410x bug fix

### PR DESCRIPTION
**Pull request by marshmellow42**

### CODE REVIEW

**Comment by holiman** [comment]
Dont forget to set your editor to use tabs. Keep it up!

**Comment by marshmellow42** [comment]
I didn't want to mass convert, so I've kept it the same wherever I edit.  I can convert as I make changes if you want...  Any new files from now on certainly will be tabs

**Comment by iceman1001** [comment]
:)  Better late than never

**Comment by marshmellow42** [comment]
Just makes it harder to merge code if anyone else is working on it

**Comment by holiman** [comment]
That's fine then. I agree it makes tracking changes/merging more difficult.

**Comment by marshmellow42** [comment]
I can do a one and done pull to change the 3 files I usually work with entirely to tab spacing: cmddata.c, lfdemod.c, lfops.c  (granted a lot of the code in cmddata.c and lfops.c that are spaces were not me :) )  that would make it easier as the files are not even consistent within themselves.

**Comment by iceman1001** [comment]
It's known for a long time,  somewhere along the line it got tangled up.

**Comment by marshmellow42** [comment]
much of the code pre-dates the Hacking.txt file.  so it did not get tangled up it just never got updated after the standards were set (agreed upon?).  and when editing a file that is already in spaces it looks funny to add one line as tabs..  so unless I will create a bunch of work for someone who wants to merge a bunch of code in the 4 files I've been working on, i'll just convert them in one commit and pull it.  we can continue the discussion on the pull request if there is any reason not to accept it we just won't...

**Pull request merged**
