### PR TITLE
Fix brew user compile problem

### PR DESCRIPTION
**Pull request by bigboyq**
Add readline, qt5 compile support for those user who is using brew under OS X environment.

If using other way to compile, without readline or qt5 installed by brew, might not face problems.

### CODE REVIEW

**Comment by iceman1001** [comment]
Nice, now we only need someone with OS X who can verify this PR, so it doesn't break old QT4 functionality.

**Comment by eelsivart** [comment]
First time proxmark user. I tried compiling with the base branch and I got some compiling errors. I then tried this update with the Elechouse Proxmark3 Dev Kit v2 and it seemed to compile and work fine. On OS X El Capitan.

**Comment by iceman1001** [comment]
On OS X,
what does the variable qtplatform contain if you run this 

MOC = $(shell pkg-config --variable=moc_location QtCore)
qtplatform = $(shell $(MOC) -v)

**Comment by eelsivart** [comment]
I get "No package 'QtCore' found" when running pkg-config. 

QT5 was installed with brew.

**Comment by bigboyq** [comment]
I have tried, no conflicts with #191 
Without #191, compile successful, but Build with no GUI
With #191, QT5 works correctly

```
pkg-config --variable=moc_location QtCore
Package QtCore was not found in the pkg-config search path.
Perhaps you should add the directory containing `QtCore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'QtCore' found
```

```
pkg-config --variable=moc_location Qt5Core
Package Qt5Core was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5Core.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5Core' found
```

```
export PKG_CONFIG_PATH=/usr/local/Cellar/qt5/5.6.1-1/lib/pkgconfig/
pkg-config --variable=moc_location Qt5Core
/usr/local/Cellar/qt5/5.6.1-1/bin/moc
```

```
export PKG_CONFIG_PATH=/usr/local/Cellar/qt5/5.6.1-1/lib/pkgconfig/
pkg-config --variable=moc_location QtCore
Package QtCore was not found in the pkg-config search path.
Perhaps you should add the directory containing `QtCore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'QtCore' found
```

BTW, there is no file named QtCore.pc in my machine

**Comment by iceman1001** [comment]
@bigboyq  Would you mind testing out the following changes to your makefile. 
http://pastebin.com/ezJRY83P
It may need some twisting from your side.

**Comment by bigboyq** [comment]
@iceman1001 can you give me a direct file client/Makefile to make sure I don't have wrong changes

**Comment by bigboyq** [comment]
Reverse to origin:master, reverse modification to Qt5Core.pc
Modified client/Makefile as @iceman1001 requested.
Got

```
gcc -std=c99 -I. -I../include -I../common -I../zlib -I/opt/local/include -I../liblua -Wall  -g -O4 -I/usr/include/malloc/ -I/usr/local/opt/readline/include -DHAVE_GUI -DZ_SOLO -DZ_PREFIX -DNO_GZIP -DZLIB_PM3_TUNED  -c -o obj/sha1.o ../common/sha1.c
clang: warning: -O4 is equivalent to -O3
g++  -Wall -O3 -c -o obj/proxgui.o proxgui.cpp
In file included from proxgui.cpp:12:
./proxguiqt.h:11:10: fatal error: 'QApplication' file not found
#include <QApplication>
         ^
1 error generated.
make[1]: *** [obj/proxgui.o] Error 1
make: *** [client/all] Error 2
```

**Comment by pwpiwi** [comment]
Homebrew tap has been added meanwhile. Lots of unrelated changes in your commits.

Closing because outdated.

**Pull request closed without merging**
