### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by k02a**
Some variable type changes.

### CODE REVIEW

**Comment by iceman1001** [comment]
Thank you for this PR,  never too late to clean up the PM3 code :)

**Comment by k02a** [comment]
Thanks iceman, hugh lots of code cleanup and optimisation is needed on this project. Step by step...

**Comment by iceman1001** [comment]
It all comes down to what is most important.  If you have the time, sure go for code clean up..
but new feature beats code clean up every day in this project ;)
if you want some suggestions, I have a long wish list :)
Thank you for your effort, I'm glad you took time to fix this.

**Comment by k02a** [comment]
I agree with you regarding the prioritation point of view. I have very little time as most of us, but if I come up with some great idea or improvement, I will surely think of posting it on your iceman1001-fork. :)

**Pull request merged**
