### PR TITLE
hardnested: dramatically reduce required disk space for tables

### PR DESCRIPTION
**Pull request by pwpiwi**
hardnested: reduce disk space for tables (by > 700MBytes) and other m…inor changes

- compress tables
- minor changes to progress reporting
- free memory on aborts (@iceman1001)

### CODE REVIEW

**Comment by pwpiwi** [comment]
Please elaborate. I don't understand your question.

**Comment by pwpiwi** [comment]
You mean compiling the tables into the executable? Tthis would require adding the (compressed) tables plus the zlib code. The executable would increase from 3 to 11MB. Not sure about the advantages.

**Comment by iceman1001** [comment]
No,  I mean _inflate_malloc_  ,  _inflate_free_  functions etc.   Why not keep all in one place?
You have some in fpgaloader.c, start.c  and now in hardnested.

**Comment by pwpiwi** [comment]
Those are all small and quite different. The common code is in the zlib directory.

**Pull request merged**
