### PR TITLE
FIX:  pins in floating state

### PR DESCRIPTION
**Pull request by iceman1001**
FIX: start up,MUXSEL_HIPKD(PA19),MUXSEL_LOPKD(PA20) are floating state. 
Needs to be  set in push-pull state

added configuration of mux.

### CODE REVIEW

**Comment by iceman1001** [comment]
@pwpiwi 
Changes to FPGA, at start up initialize these PIN as push-pull state is also needed.

**Comment by iceman1001** [comment]
@pwpiwi   merge please.

**Comment by pwpiwi** [comment]
Ummh, let me read the product manual first. I cannot memorize all the peripherals functions. This shouldn't be pressing after we have survived so many years.

**Comment by pwpiwi** [comment]
As I don't like duplicating code: why not `SetAdcMuxFor(GPIO_MUXSEL_HIPKD)`?

**Comment by iceman1001** [comment]
Why set the HF peakdetector ?

**Comment by pwpiwi** [comment]
Why not? Choose any input.

**Comment by iceman1001** [comment]
Why set any input for the ADC when init?
They should be all disconnected when not in use.
redundant code removed.

**Comment by pwpiwi** [comment]
You wanted to avoid floating pins. If you don't select any input, the output of the Mux will be floating...

**Pull request closed without merging**
