### PR TITLE
Emv commands work with smartcard interface (RfidResearchGroup PR67 by…

### PR DESCRIPTION
**Pull request by pwpiwi**
… @Merlokk)

* replace 'hf emv' commands by 'emv' commands
* Enable smartcard commands by default (-DWITH_SMARTCARD)
* update i2c.c from RfidResearchGroup repository
* update smartcard.c from RfidResearchGroup repository

### CODE REVIEW

**Comment by pwpiwi** [comment]
@merlokk or someone else with an RDV4.0: could you please test if I missed anything?

**Comment by merlokk** [comment]
ill test it after ny.

**Comment by merlokk** [comment]
not works( ill check why

**Comment by merlokk** [comment]
1. needs a new version of i2c.c and maybe i2c.h (there is a new command for t=0)

**Comment by pwpiwi** [comment]
Your own comments to the PR were

* emv scan not works with sc at all. It needs to rebuild some parts.
* emv exec works, but for me only up to GPO
* the rest commands works (at least put data to interface and receive data)

Same should apply here. The new command for t=0 and changes in apdu logic had been added later. More (but easier) PRs will follow.

**Comment by merlokk** [comment]
maybe makes sense.
now all this part is not completed yet(
here will be 3 parts:
1. pse sfi works (now completed)
2. sda/dda hash check (dont know why but it not works for contact transactions)
3. full VSDC transaction logic (not implemented at all( )

**Comment by merlokk** [comment]
and that changes in RRG repo....

**Comment by merlokk** [comment]
here is a big PR maybe makes sense to merge it and then next up to date

**Comment by pwpiwi** [comment]
Does this PR break anything? Do the RFID emv commands still work?

**Comment by pwpiwi** [comment]
... and the sc commands?

**Comment by merlokk** [comment]
contactless works.
sc works as in original code.

**Pull request merged**
