### PR TITLE
Experimental HitagS support

### PR DESCRIPTION
**Pull request by spenneb**
We presented our work on the HitagS at the 32c3. This is the experimental code for the proxmark.
https://events.ccc.de/congress/2015/Fahrplan/events/7166.html

Please review and merge.

### CODE REVIEW

**Comment by iceman1001** [comment]
Great work!  
I've been into the SAT solver <-> PM3 but never figured out how to use it properly. 

Back to commit,  I'm missing the new USB_COMMANDS in the commands.lua lib.

**Comment by holiman** [comment]
Wow, very interesting! I'll try to take some time to look into this and check out the presentation. Thanks!

**Comment by spenneb** [comment]
English version:
http://cdn.media.ccc.de/congress/2015/h264-hd-web/32c3-7166-en-Sicherheit_von_125kHz_Transpondern_am_Beispiel_Hitag_S.mp4

**Comment by holiman** [comment]
Sorry it took so long. I'll merge this asap, but could you please add some info into CHANGELOG.md? The changelog should be a short description about the new feature, and possibly you could add a link to further info (e.g. the presentation). You're welcome to add your names for credit in there, for everlasting glory :)

**Comment by spenneb** [comment]
Hi holiman.
I just added to CHANGELOG.md

Thanks a lot.

**Pull request merged**
