### PR TITLE
Khorben/warnings

### PR DESCRIPTION
**Pull request by khorben**
Hi Proxmark people, these two commits avoid a few warnings while compiling proxmark3.
Cheers,
-- khorben

### CODE REVIEW

**Comment by iceman1001** [comment]
On which OS / dev environment do you get those warnings?  
on ubuntu I get three warnings,  2 for ishexdigit  (your ctype.h)  and 1 for %d is not long int...

**Comment by khorben** [comment]
I'm compiling on NetBSD/amd64 with GCC 4.8.5.

**Comment by pwpiwi** [comment]
I don't see a point in casting `char` to `unsigned char` for a function which is defined as `int isspace(int)`. Agree with @iceman1001. Please change your PR accordingly.

**Comment by iceman1001** [comment]
@khorben  Would you please change the PR according to given feedbacks.

**Comment by khorben** [comment]
I need a moment to properly explain, sorry. On NetBSD the manual page for ctype(3) briefly summarizes the issue. Basically `char` is signed by default, so without an explicit cast to `unsigned char`, any non-ASCII character (e.g. anything UTF-8) will be sign extended to a negative value, which is wrong.
Therefore in this case the compiler warning `array subscript has type 'char' [-Wchar-subscripts]` is an important one, as the corresponding code will break on any non-ASCII character.

**Comment by pwpiwi** [comment]
Thanks for the explanation. I would expect that there are many functions in util.c which won't work for multi byte characters.

**Pull request merged**
