### PR TITLE
Update/cleanup Makefiles

### PR DESCRIPTION
**Pull request by pwpiwi**
- add new target "make mfkey" to build mfkey32 and mfkey64
- include above when "make all"
- fix Qt detection for Kali Linux
- create and use dependency files when building client
- create client/lualibs/usb_cmd.lua from include/usb_cmd.h when building client
- add Windows *.exe files with "make tarbin"
- For the time being don't include Makefile.common in Makefile and client/Makefile
- set com3 as default flashing port for Windows (including mingw)
- remove static targets snooper and cli. Remove their sources as well.

### CODE REVIEW

**Comment by pwpiwi** [comment]
Did you test graphing on Kali as well? Qt4 or Qt5?

**Comment by marshmellow42** [comment]
I didn't test the graph yet on Kali..  will do so in an hour or two.

**Comment by marshmellow42** [comment]
What qt version did you test?  I'll grab the other :)

**Comment by marshmellow42** [comment]
QT version 4.8.7 works fine in kali.  graphing works fine.

**Comment by pwpiwi** [comment]
Same here. Qt4 compiles and runs fine. Qt5 requests to compile with -fPIC, throws lots of warnings at run time and finally crashes.

**Comment by marshmellow42** [comment]
I didn't need to change any environments and I never explicitly installed awk, so it is included?

**Comment by pwpiwi** [comment]
The Posix standards defines some tools to be included with a Unix. awk is one of them. It therefore should be there without the need to install it separately.

**Pull request merged**
