### PR TITLE
Improve 'Magic' Mifare tags generation detection & hf mf c* commands magic 4k compatibility

### PR DESCRIPTION
**Pull request by Fl0-0**
I had some problems to identify some backdoored  Miafre tags: 

- A magic 4k (identified as GEN 1b in icemann fork)
- A magic 1k with a "#db# halt error. response len: 1"

I've change the logic of testing wupC1 and wupC2 commands in armsrc/mifarecmd.c:
- isOK set to 0 by default, set to 1 at least if one magic command works (with the old logic, if wupC1 command fails isOK is set to 0 even if  wupC2 is OK)
- removed the "if" on mifare_classic_halt(): like in ceman1001 fork: removed the if,  since some magic tags misbehaves and send an answer to it

Before:
```
Prox/RFID mark3 RFID instrument          
bootrom: master/v2.2.0-552-gebe9a3b-dirty-suspect 2017-07-04 12:04:03
os: master/v2.2.0-552-gebe9a3b-dirty-suspect 2017-07-04 12:04:04
LF FPGA image built for 2s30vq100 on 2015/03/06 at 07:38:04
HF FPGA image built for 2s30vq100 on 2017/05/17 at 17:48:26
          
uC: AT91SAM7S256 Rev B          
Embedded Processor: ARM7TDMI          
Nonvolatile Program Memory Size: 256K bytes. Used: 193020 bytes (74%). Free: 69124 bytes (26%).          
Second Nonvolatile Program Memory Size: None          
Internal SRAM Size: 64K bytes          
Architecture Identifier: AT91SAM7Sxx Series          
Nonvolatile Program Memory Type: Embedded Flash Memory          
proxmark3> hf search
          
 UID : c0 xx xx xx           
ATQA : 00 04          
 SAK : 08 [2]          
TYPE : NXP MIFARE CLASSIC 1k | Plus 2k SL1          
proprietary non iso14443-4 card found, RATS not supported          
**#db# halt error. response len: 1          
Answers to chinese magic backdoor commands: NO**          

Valid ISO14443A Tag Found - Quiting Search
          
proxmark3> hf search
          
 UID : ac xx xx xx           
ATQA : 00 02          
 SAK : 18 [2]          
TYPE : NXP MIFARE Classic 4k | Plus 4k SL1          
proprietary non iso14443-4 card found, RATS not supported          
**Answers to chinese magic backdoor commands: NO**          

Valid ISO14443A Tag Found - Quiting Search
```

After:

```
Prox/RFID mark3 RFID instrument          
bootrom: Magic_MF_Detect/v3.0.1-45-g0f6838d-suspect 2017-07-05 08:00:41
os: Magic_MF_Detect/v3.0.1-45-g0f6838d-suspect 2017-07-05 08:00:42
LF FPGA image built for 2s30vq100 on 2015/03/06 at 07:38:04
HF FPGA image built for 2s30vq100 on 2017/05/17 at 17:48:26
          
uC: AT91SAM7S256 Rev B          
Embedded Processor: ARM7TDMI          
Nonvolatile Program Memory Size: 256K bytes. Used: 193010 bytes (74%). Free: 69134 bytes (26%).          
Second Nonvolatile Program Memory Size: None          
Internal SRAM Size: 64K bytes          
Architecture Identifier: AT91SAM7Sxx Series          
Nonvolatile Program Memory Type: Embedded Flash Memory          
proxmark3> hf search
          
 UID : ac xx xx xx           
ATQA : 00 02          
 SAK : 18 [2]          
TYPE : NXP MIFARE Classic 4k | Plus 4k SL1          
proprietary non iso14443-4 card found, RATS not supported          
**Answers to chinese magic backdoor commands: YES**          

Valid ISO14443A Tag Found - Quiting Search
          
proxmark3> hf search
          
 UID : c0 xx xx xx           
ATQA : 00 04          
 SAK : 08 [2]          
TYPE : NXP MIFARE CLASSIC 1k | Plus 2k SL1          
proprietary non iso14443-4 card found, RATS not supported          
**#db# halt error. response len: 1          
Answers to chinese magic backdoor commands: YES**          

Valid ISO14443A Tag Found - Quiting Search
          
proxmark3> 
```

### CODE REVIEW

**Comment by iceman1001** [comment]
Not sure, but your magic s70/4k tag is indeed a magic card, gen1b?   ie correct identified in icemanfork?
and the missbehaving magic s50/1k tag also got correct identified in icemanfork?

Is so, why not just take the working parts from icemanfork and commit those instead?

**Comment by Fl0-0** [comment]
Hello iceman1001

- yes my  s70/4k tag is indeed a magic card identified as gen1b in your fork.
- yes the misbehaving magic s50/1k tag is correct identified in your fork.

Because:
1. The changed logic is the same as in your fork but without the goto: label: :-)
2. identifying and printing  generation in the client is cool but I've not tested it, maybe it should be added like in your fork

**Comment by iceman1001** [comment]
I suggest you use the same identification og Gen1a/ 1b/2   since there are differences between those ones. 
Among one, if you leave it like you have it,  users might think they use **hf mf c..**  commands and start questions on the outputs.  
Its why I have defined the different magic versions,  so users can easily identify and properly use them.

If you have a good gen2 detection,  feel free to add it aswell :)

**Comment by Fl0-0** [comment]
OK after some tests:
With some debuging:
- My Gen1a Mifare 1k answers to 0x40 and 0x43 commands
- My Gen1b Mifare 4k answers only to 0x40 command

Looking at the libnfc code [https://github.com/nfc-tools/libnfc/commit/6c44c20ffce6b4f2e725f13fbb3fc49f6ae6d1bf](https://github.com/nfc-tools/libnfc/commit/6c44c20ffce6b4f2e725f13fbb3fc49f6ae6d1bf) , that they only send 0x40 command for the 4k.

My 4k card works fine with it:
```
Found MIFARE Classic card:
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 00  00  
       UID (NFCID1): 00  00  00  00  
      SAK (SEL_RES): 18  
Guessing size: seems to be a 4096-byte card
Sent bits:     50  00  57  cd  
Sent bits:     40 (7 bits)
Warning: Unlock command [1/2]: failed / not acknowledged.
Writing 256 blocks |................................................................................................................................................................................................................................................................| 
```

What is gen2 ?

**Comment by iceman1001** [comment]
yes,  that is the difference between 1a/1b .
Generation2,  is the magic tags which doesn't use backdoor commands.  ie, can be used with a phone for instance.

**Comment by Fl0-0** [comment]
Unfortunately, I don't have such tags !

cload and csave suffer the same problem as "misbehaving magic s50/1k tag halt error"

Maybe i should patch it too by commenting the break ?

**Comment by Fl0-0** [comment]
With the  misbehaving magic s50/1k tag :

Before:
```
proxmark3> hf search
          
 UID : aa 44 bf 0e           
ATQA : 00 04          
 SAK : 08 [2]          
TYPE : NXP MIFARE CLASSIC 1k | Plus 2k SL1          
proprietary non iso14443-4 card found, RATS not supported          
#db# halt error. response len: 1          
Answers to chinese magic backdoor commands: NO       

Valid ISO14443A Tag Found - Quiting Search
          
proxmark3> hf mf csave
#db# halt error. response len: 1          
#db# Halt error          
Cant get block: 0          
#db# halt error. response len: 1          
#db# Halt error          
Cant get block: 63     
Saved to file: dump.eml
proxmark3> hf mf cload test
#db# halt error. response len: 1          
#db# Halt error          
Can't set magic card block: 63
```

now:
```
proxmark3> hf search
          
 UID : aa 44 bf 0e           
ATQA : 00 04          
 SAK : 08 [2]          
TYPE : NXP MIFARE CLASSIC 1k | Plus 2k SL1          
proprietary non iso14443-4 card found, RATS not supported          
#db# halt error. response len: 1          
Answers to chinese magic backdoor commands (GEN 1a): YES 

Valid ISO14443A Tag Found - Quiting Search
          
proxmark3> hf mf csave
#db# halt error. response len: 1          
#db# Halt error          
#db# halt error. response len: 1          
#db# Halt error          
Saved to file: aa44bf0e5f0804.eml          
proxmark3> hf mf cload aa44bf0e5f0804
#db# halt error. response len: 1          
#db# Halt error          
Loaded from file: aa44bf0e5f0804.eml
```

**Comment by Fl0-0** [comment]
Why not Implementing hf mf cload /csave for 4k gen1b ? it should not be so hard to do?

**Comment by Fl0-0** [comment]
Hello, i'm looking for a way to make hf mf c working for gen1b tags.
My idea is to set up a new flag like:

#define CSETBLOCK_MAGIC_1B 0x20

as bit 5,6,7 are free.

Then before using hf mf c* commands, detect the generation of magic tags and by setting the flag if gen1b is detected do not issue the 0x43 command in MifareCSetBlock()and MifareCGetBlock().

What do you think ?

**Comment by pwpiwi** [comment]
Doesn't the @iceman1001 branch support writing of Gen1b tags?

**Comment by marshmellow42** [comment]
I think an auto detect is going to be problematic.  At some antenna to chip distances the pm3 may miss the response and improperly id the chip.

**Comment by Fl0-0** [comment]
- Doesn't the @iceman1001 branch support writing of Gen1b tags?
Nope, hf mf c* commands work only with gen1a )-:

```
pm3 --> hf search
          
 UID : AC 02 E3 0C           
ATQA : 00 02          
 SAK : 18 [2]          
TYPE : NXP MIFARE Classic 4k | Plus 4k SL1          
proprietary non iso14443-4 card found, RATS not supported          
Answers to magic commands (GEN 1b): YES          
Prng detection: WEAK          

Valid ISO14443-A Tag Found - Quiting Search
          
pm3 --> hf mf cgetblk 0
--block number: 0           
#db# wupC2 error          
Can't read block. error=2
```

- I think an auto detect is going to be problematic.
I was thinking of making a test for gen1b, but using gen1a unlock method by default or in case of failure.

**Comment by Fl0-0** [comment]
hf mf c* commands works for Gen1b tag (for my 4k gen1b, cload, csave and cgetsc works only for 1k part of the 4k)

**Comment by Fl0-0** [comment]
Made hf mf cgetsc works for 4k

```
proxmark3> hf mf csetblk 240 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Chinese magic backdoor command (GEN 1b) detected          
--block number:240 data:aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa           
#db# halt error. response len: 1          
#db# Halt error          
proxmark3> hf mf cgetsc 39
--sector number:39           
Chinese magic backdoor command (GEN 1b) detected          
block 240 data:aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa           
block 241 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
block 242 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
block 243 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
block 244 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
block 245 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
block 246 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
block 247 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
block 248 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
block 249 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
block 250 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
block 251 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
block 252 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
block 253 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
block 254 data:ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff           
#db# halt error. response len: 1          
#db# Halt error          
block 255 data:ff ff ff ff ff ff ff 07 80 69 ff ff ff ff ff ff
```

**Comment by pwpiwi** [comment]
Are those halt errors to be expected? If yes, can we suppress them?

**Comment by Fl0-0** [comment]
There are here because the tag responds to halt command, i can suppress them.

**Comment by Fl0-0** [comment]
OK it is ready for testing:

- gen1a backdoor detection  missbehaving magic s50/1k tag 
- backdoor detection for gen1b (tested on my 4K)
- hf mf c* commands works with gen1a and gen1b backdoors
- hf mf c* commands like (csetblk, cload ans csave) now are 4k compatible 

```
proxmark3> hf search
          
 UID : 00 00 00 00           
ATQA : 00 02          
 SAK : 18 [2]          
TYPE : NXP MIFARE Classic 4k | Plus 4k SL1          
proprietary non iso14443-4 card found, RATS not supported          
Answers to chinese magic backdoor commands (GEN 1b): YES          

Valid ISO14443A Tag Found - Quiting Search
          
proxmark3> hf mf cgetsc 0
--sector number:0           
Chinese magic backdoor command (GEN 1b) detected          
block   0 data:00 00 00 00 00 98 02 00 00 00 00 00 00 00 00 00           
block   1 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block   2 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block   3 data:ff ff ff ff ff ff ff 07 80 69 00 00 00 00 00 00           
proxmark3> hf mf csetuid 0a5b7fd0
--wipe card:NO  uid:0a 5b 7f d0           
Chinese magic backdoor command (GEN 1b) detected          
old block 0:  00 00 00 00 00 98 02 00 00 00 00 00 00 00 00 00           
new block 0:  0a 5b 7f d0 fe 98 02 00 00 00 00 00 00 00 00 00           
old UID:00 00 00 00           
new UID:0a 5b 7f d0           
proxmark3> hf search
          
 UID : 0a 5b 7f d0           
ATQA : 00 02          
 SAK : 18 [2]          
TYPE : NXP MIFARE Classic 4k | Plus 4k SL1          
proprietary non iso14443-4 card found, RATS not supported          
Answers to chinese magic backdoor commands (GEN 1b): YES          

Valid ISO14443A Tag Found - Quiting Search
          
proxmark3> hf mf cgetsc 0
--sector number:0           
Chinese magic backdoor command (GEN 1b) detected          
block   0 data:0a 5b 7f d0 fe 98 02 00 00 00 00 00 00 00 00 00           
block   1 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block   2 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block   3 data:ff ff ff ff ff ff ff 07 80 69 00 00 00 00 00 00                   
proxmark3> hf mf cgetblk 255
Chinese magic backdoor command (GEN 1b) detected          
--block number:255           
block data:ff ff ff ff ff ff ff 07 80 69 00 00 00 00 00 00           
proxmark3> hf mf cgetsc 39
--sector number:39           
Chinese magic backdoor command (GEN 1b) detected          
block 240 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 241 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 242 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 243 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 244 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 245 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 246 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 247 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 248 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 249 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 250 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 251 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 252 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 253 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 254 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 255 data:ff ff ff ff ff ff ff 07 80 69 00 00 00 00 00 00           
proxmark3> hf mf csetblk 255 a1a2a3a4a5a6ff078069000000000000
Chinese magic backdoor command (GEN 1b) detected          
--block number:255 data:a1 a2 a3 a4 a5 a6 ff 07 80 69 00 00 00 00 00 00           
proxmark3> hf mf cgetsc 39
--sector number:39           
Chinese magic backdoor command (GEN 1b) detected          
block 240 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 241 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 242 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 243 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 244 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 245 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 246 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 247 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 248 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 249 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 250 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 251 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 252 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 253 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 254 data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00           
block 255 data:a1 a2 a3 a4 a5 a6 ff 07 80 69 00 00 00 00 00 00           
proxmark3> hf mf csave e 4
Chinese magic backdoor command (GEN 1b) detected          
Saving magic mifare 4K                 
proxmark3> hf mf ekeyprn 4
|---|----------------|----------------|          
|sec|key A           |key B           |          
|---|----------------|----------------|          
|000|  ffffffffffff  |  000000000000  |          
|001|  ffffffffffff  |  000000000000  |          
|002|  ffffffffffff  |  000000000000  |          
|003|  ffffffffffff  |  000000000000  |          
|004|  ffffffffffff  |  000000000000  |          
|005|  ffffffffffff  |  000000000000  |          
|006|  ffffffffffff  |  000000000000  |          
|007|  ffffffffffff  |  000000000000  |          
|008|  ffffffffffff  |  000000000000  |          
|009|  ffffffffffff  |  000000000000  |          
|010|  ffffffffffff  |  000000000000  |          
|011|  ffffffffffff  |  000000000000  |          
|012|  ffffffffffff  |  000000000000  |          
|013|  ffffffffffff  |  000000000000  |          
|014|  ffffffffffff  |  000000000000  |          
|015|  ffffffffffff  |  000000000000  |          
|016|  ffffffffffff  |  000000000000  |          
|017|  ffffffffffff  |  000000000000  |          
|018|  ffffffffffff  |  000000000000  |          
|019|  ffffffffffff  |  000000000000  |          
|020|  ffffffffffff  |  000000000000  |          
|021|  ffffffffffff  |  000000000000  |          
|022|  ffffffffffff  |  000000000000  |          
|023|  ffffffffffff  |  000000000000  |          
|024|  ffffffffffff  |  000000000000  |          
|025|  ffffffffffff  |  000000000000  |          
|026|  ffffffffffff  |  000000000000  |          
|027|  ffffffffffff  |  000000000000  |          
|028|  ffffffffffff  |  000000000000  |          
|029|  ffffffffffff  |  000000000000  |          
|030|  ffffffffffff  |  000000000000  |          
|031|  ffffffffffff  |  000000000000  |          
|032|  ffffffffffff  |  000000000000  |          
|033|  ffffffffffff  |  000000000000  |          
|034|  ffffffffffff  |  000000000000  |          
|035|  ffffffffffff  |  000000000000  |          
|036|  ffffffffffff  |  000000000000  |          
|037|  ffffffffffff  |  000000000000  |          
|038|  ffffffffffff  |  000000000000  |          
|039|  a1a2a3a4a5a6  |  000000000000  |          
|---|----------------|----------------|          
proxmark3> hf mf csave test 4
Chinese magic backdoor command (GEN 1b) detected          
Saving magic mifare 4K          
Saved to file: test.eml  
```

**Comment by merlokk** [comment]
where you have bought it? drop address pls  by mail olegmsn@gmail.com

**Comment by iceman1001** [comment]
The first generation 1B /s50  I saw came from www.lab401.com   (http://www.proxmark.org/forum/viewtopic.php?id=3137)

**Comment by Fl0-0** [comment]
Yes that's where i bought it !
[https://lab401.com/mifare/10-mifare-4k-uid-modifiable.html](https://lab401.com/mifare/10-mifare-4k-uid-modifiable.html)

**Comment by merlokk** [comment]
thanks)

**Comment by Fl0-0** [comment]
Yes.
I can revert to MF_DBG_ERROR level in  mifare_classic_halt() and don't issue the halt command for gen1b, but misbehaving magic s50/1k tag will still display these halt errors.

Is this acceptable ?

**Comment by pwpiwi** [comment]
As I am converted: yes.

**Comment by Fl0-0** [comment]
Ok !

**Comment by pwpiwi** [comment]
Please add a line to CHANGELOG.md and we are ready to merge.

**Comment by Fl0-0** [comment]
OK pwpiwi, done.

**Pull request merged**
