### PR TITLE
ISO 14443 type B support for (German) electronic ID cards

### PR DESCRIPTION
**Pull request by frederikmoellers**
This adds 2 new functions to iso14443b.c: iso14443b_setup and iso14443b_apdu which perform tasks similar to their counterparts in iso14443a.c. On the long run this should facilitate building functionality that is type-independent (i.e. supports both A and B tags).
As a first implementation, the functionality related to the German ID card (epa.c) has been updated to support both types.
Experiments so far show that both types work fine and can be used for the same tasks.

### CODE REVIEW

**Comment by marshmellow42** [comment]
nice, i'll have to give it a run after merging it with my 14b minor adjustments!

**Comment by holiman** [comment]
Nice work. Would you mind adding some short note within CHANGELOG.md also, describing what is new (from a user-perspective)?

**Comment by frederikmoellers** [comment]
I will, thanks for pointing that out.

**Comment by iceman1001** [comment]
@frederikmoellers  I noticed your extended timeout when sendind/reading apdu's.
I have a problem with getting my apdu for 14443-b to work, so I'm thinking this timeout might be a solution.  How did you come to this number/limit?

**Comment by frederikmoellers** [comment]
@iceman1001 Honestly it was just trial&error. I didn't get a response from the tag at first, but the log showed that the initial steps of the anticollision procedure (WUPB and ATTRIB) did work. What struck me as odd was that the proxmark returned much faster than it did when communicating with A cards. So I just increased the timeouts and voilá, I got a response. I then fiddled around with the exact values and found a factor of 100 to give the best results.

**Comment by iceman1001** [comment]
I've the same issue with the 14b commands where I am sending a iso7816 after a successful wupb, attrib, I don't get thet tags answer..
In the EPA I can understand since it has at lot of crypto/mac to do.

**Comment by frederikmoellers** [comment]
@holiman I added a note to CHANGELOG.md

**Pull request merged**
