### PR TITLE
HF snoop ported by enio's repository

### PR DESCRIPTION
**Pull request by etmatrix**
Hi, I ported Enio's patch for HF snoop in latest git, so now PM3 can snoop a generic HF signal and show a graph. There are some improvements todo, but is working.
In this release there are also bit files for FPGA, they are created with ISE WebPack 10.1 SP3 for linux.
With my friend meter in forum proxmark, I have done many tests on LF and HF, they work without errors, so my changes in FPGA should not have done breaks.
I hope you like it.

### CODE REVIEW

**Comment by iceman1001** [comment]
I tried these changes, but I can't get the "hf snoop" to work.  It could be the fpga images, is it the new compiled ones?

**Comment by iceman1001** [comment]
Ignore my earlier comment, I got it to work.

**Comment by etmatrix** [comment]
sure I commited also fpga/fpga_*.bit you should see new date 2015/10/22 with hw ver command.
My friend meter tried it and report result here http://proxmark.org/forum/viewtopic.php?id=2675

**Comment by etmatrix** [comment]
ok I just answered.... :)

**Comment by pwpiwi** [comment]
Excellent. This will become a great debugging tool. Some remarks and suggestions:
- FPGA: I don't see the purpose of `ant_low`. It should be possible to delete it.
- FPGA: Why the `always @(ck_1356meg, pck0) // should synthetisize to a mux..`? It should be possible to simply assign `adc_clk` and `ssp_clk`
- FPGA: The FPGA code generates a `ssp_frame` signal every 8 Bits while the C code uses 16Bit transfers. This might lead to swapped bytes.

**Comment by etmatrix** [comment]
Thank you for your suggestions.
1. sure I removed it
2. assigned
3. I don't know very well the architecture, my work is a simple porting.
So this setting in hfsnoop.c 
AT91C_BASE_SSC->SSC_RFMR = SSC_FRAME_MODE_BITS_IN_WORD(16); // Setting Frame mode, 16 bits per word
is dangerous?
I will try without changing the frame size, so we should have also a double buffer size.

**Comment by pwpiwi** [comment]
Re 3.: Leave it as it is. I was wrong. We won't have swapped bytes. Since there are no "high" and "low" bytes it doesn't matter if odd or even bytes come first in the 16 Bit frame.

**Comment by etmatrix** [comment]
1 and 2 after the changes snoop is not working, for now I don't commit my new changes.

**Comment by pwpiwi** [comment]
Did you remove the respective `reg` declarations as well?

**Comment by etmatrix** [comment]
sure I removed

    reg ssp_clk = 1'b0;
    reg adc_clk;
    ...
    always @(ck_1356meg, pck0) // should synthetisize to a mux..
      begin
        adc_clk = ck_1356meg;
        ssp_clk = ~ck_1356meg;
      end

and replaced with

    assign adc_clk = ck_1356meg;
    assign ssp_clk = ~ck_1356meg;

**Comment by pwpiwi** [comment]
1. found another issue: in the modified Makefile you had added hi_sniffer.v to the lo files. Please fix.
2. This should work as a minimized hi_sniffer.v without unnecessary overhead. Please test and - if it works - add to your next commit:
```
module hi_sniffer(
    pck0, ck_1356meg, ck_1356megb,
    pwr_lo, pwr_hi, pwr_oe1, pwr_oe2, pwr_oe3, pwr_oe4,
    adc_d, adc_clk,
    ssp_frame, ssp_din, ssp_dout, ssp_clk,
    cross_hi, cross_lo,
    dbg,
    xcorr_is_848, snoop, xcorr_quarter_freq // not used.
);
    input pck0, ck_1356meg, ck_1356megb;
    output pwr_lo, pwr_hi, pwr_oe1, pwr_oe2, pwr_oe3, pwr_oe4;
    input [7:0] adc_d;
    output adc_clk;
    input ssp_dout;
    output ssp_frame, ssp_din, ssp_clk;
    input cross_hi, cross_lo;
    output dbg;
    input xcorr_is_848, snoop, xcorr_quarter_freq; // not used.

// We are only snooping, all off.
assign pwr_hi  = 1'b0;
assign pwr_lo  = 1'b0;
assign pwr_oe1 = 1'b0;
assign pwr_oe2 = 1'b0;
assign pwr_oe3 = 1'b0;
assign pwr_oe4 = 1'b0;

reg ssp_frame;
reg [7:0] adc_d_out = 8'd0;
reg [2:0] ssp_cnt = 3'd0;

assign adc_clk = ck_1356meg;
assign ssp_clk = ~ck_1356meg;

always @(posedge ssp_clk)
begin
	if(ssp_cnt[2:0] == 3'd7)
		ssp_cnt[2:0] <= 3'd0;
	else
		ssp_cnt <= ssp_cnt + 1;

	if(ssp_cnt[2:0] == 3'b000) // set frame length
		begin
			adc_d_out[7:0] <= adc_d;
			ssp_frame <= 1'b1;
		end
	else
		begin
			adc_d_out[7:0] <= {1'b0, adc_d_out[7:1]};
			ssp_frame <= 1'b0;
		end
	
end

assign ssp_din = adc_d_out[0];

endmodule
```

**Comment by etmatrix** [comment]
now is working, @pwpiwi thank you for your big help

**Comment by pwpiwi** [comment]
Just one minor thing left: please add some words to CHANGELOG.md

**Comment by etmatrix** [comment]
done

**Comment by EnioArda** [comment]
Oh nice to see, im glad you cleaned the code too as it was kinda wip i didnt get to go on with.

Just one note on that 16Bit transfer, if i remember correctly i changed it to 16 because you would loose a byte here and there in the receive loop when pushing the limits on the sample speed.

**Pull request merged**
