### PR TITLE
(implementing suggestion #94)

### PR DESCRIPTION
**Pull request by pwpiwi**
hf mf mifare: gracefully exit if tag isn't vulnerable to this attack
hf mf nested: dito

### CODE REVIEW

**Comment by pwpiwi** [comment]
```
proxmark3> hf mf mif
-------------------------------------------------------------------------
Executing command. Expected execution time: 25sec on average  :-)
Press button on the proxmark3 device to abort both proxmark3 and client.
-------------------------------------------------------------------------
......

Card is not vulnerable to Darkside attack (its random number generator is not predictable).


proxmark3>
```

**Comment by pwpiwi** [comment]
Can someone with LUA powers please change mifare_autopwn.lua accordingly?

**Comment by iceman1001** [comment]
Now that you are inside "nested", how about the issue #88  ?

**Comment by holiman** [comment]
I can fix the lua stuff when this is committed.. You expanded the isOK value in the response packet ?

**Comment by pwpiwi** [comment]
Correct. See client/cmdhfmf.c for the possible values and their meanings:
```
			switch (isOK) {
				case -1 : PrintAndLog("Button pressed. Aborted.\n"); break;
				case -2 : PrintAndLog("Card is not vulnerable to Darkside attack (doesn't send NACK on authentication requests).\n"); break;
				case -3 : PrintAndLog("Card is not vulnerable to Darkside attack (its random number generator is not predictable).\n"); break;
				default: ;
			}
```

**Pull request merged**
