### PR TITLE
iClass MAC calculation speedup (optimized_cipher.c)

### PR DESCRIPTION
**Pull request by pwpiwi**
See http://www.proxmark.org/forum/viewtopic.php?pid=36292#p36292. The MAC calculation in optimized_cipher.c was too slow (403 microseconds). This PR speeds up the calculation to 270 microseconds.

### CODE REVIEW

**Comment by marshmellow42** [comment]
Are you missing iclass.h or did I miss it?

**Comment by pwpiwi** [comment]
Both. :grin:

**Comment by iceman1001** [comment]
So where is the speedup compared to Holimans notes?
image

**Comment by pwpiwi** [comment]
That would require access to @holiman's laptop from 2015 and we would need to know the compiler version and compiler flags he had used back then.

If we assume the same speed increase on this laptop as on the Proxmark, it would take 63% of the time (= 0,095)

**Comment by iceman1001** [comment]
Impressive speedup!  Well done!

**Comment by holiman** [comment]
Nice!

**Pull request merged**
