### PR TITLE
add force_align_arg_pointer attribute to all callback functions

### PR DESCRIPTION
**Pull request by pwpiwi**
* inspired by issue #404 and respective fix PR #538
* possible fix for mysterious crashes, e.g. issue #497 and http://www.proxmark.org/forum/viewtopic.php?id=5388

### CODE REVIEW

**Comment by iceman1001** [comment]
Cool, did you experience the mysterious crashes aswell?

**Comment by pwpiwi** [comment]
No, never had this kind of issue.

**Comment by iceman1001** [comment]
This PR will need to get the attention of the ppl who experienced those crashes

**Comment by pwpiwi** [comment]
Most likely this PR - like all the others - will get the attention of most people only after it has been merged.

**Comment by iceman1001** [comment]
Well, nothing in this PR hurts anything.


_I see you are quite trigger happy with the close button..._

**Pull request merged**
