### PR TITLE
hf mf nested add some functionality

### PR DESCRIPTION
**Pull request by merlokk**
- Added `hf mf nested` mode: autosearch keys for attack (from well known keys)
- Added to `hf mf nested` source key check before attack 
- Added to `hf mf nested` after attack it checks all found keys on non-open sectors 
- small refactoring

### CODE REVIEW

**Comment by merlokk** [comment]
Is this ok?

**Comment by merlokk** [comment]
guys, have you look on it?

**Comment by merlokk** [comment]
Made compatible with lastest master

**Comment by pwpiwi** [comment]
Be patient. Checking needs some time.

**Comment by pwpiwi** [comment]
Why waiting until after the attack to check for found keys on non-open sectors? I am wondering if it wouldn't be better to check with each found key even before trying nested on a sector?

**Comment by iceman1001** [comment]
Its indeed much better to test before trying nested on a sector.  
One of the improvements on my hardnested script and my improved "checkkeys".  A test authentication takes about 5ms which is much faster than a nested attack run.

**Comment by merlokk** [comment]
it can be tested. but. it can test only "public" keys. It tests them with parameter "*".

and. it tests on the end because it tests keys that found by attack.
maybe it will be better to try each key after it have found. But it needs deep restructurization nested command.

**Comment by merlokk** [comment]
here https://github.com/merlokk/proxmark3/blob/nested-addfunct/client/cmdhfmf.c#L689 tries "public" keys before nested

**Comment by iceman1001** [comment]
I'm sure piwi didn't mean the public keys, since they already are tested but the found key from one nested attack.   If you look at the lua-script version,  it takes every new found key and put it first in the keys to test.. 
A quite neat little trick.

**Comment by merlokk** [comment]
now it needs to have command on arm side to check keys on all sectors . This cycle https://github.com/merlokk/proxmark3/blob/nested-addfunct/client/cmdhfmf.c#L829 needs to be on arm side because by now - it will be longer than nested.
is this ok?

**Comment by merlokk** [comment]
as i see in 
void MifareChkKeys(uint16_t arg0, uint8_t arg1, uint8_t arg2, uint8_t *datain) on mifarecmd.c - arm side.
there is no space to add cycle functionality. maybe high byte here?
bool clearTrace = arg1;
or it needs to add new command?

**Comment by merlokk** [comment]
Maybe lets merge this as is and after i will change MifareChkKeys to have cycle functionality

arg1 high byte will be sectors count.
and change nested and chkkeys command itself

because it may be too much changes for 1 merge.

**Pull request merged**
